inbox/mailsync/backends/imap/generic.py
This might be a quick win to reduce logging but still get an idea if an account is actively polling.
Ref https://github.com/closeio/sync-engine/issues/6
=> Log polling statement every 5 minutes to cut down on logging volume

.circleci/config.yml, requirements_lint.txt
Ran `pip freeze` on a fresh venv with just `black==19.10b0`.
```
appdirs==1.4.4
attrs==20.2.0
black==19.10b0
click==7.1.2
pathspec==0.8.0
regex==2020.9.27
toml==0.10.1
typed-ast==1.4.1
```
`black==20.8b1` still has some issues and has fewer dependencies in Python 3.7, therefore I also bumped the Python version of the image (even though it shouldn't make a difference here)
=> Update lint requirements

requirements_frozen.txt
The latest version fixes a py2/3 compatibility error with a `super(..)` call.
cc @thomasst
=> Bump AuthAlligator client version

inbox/mailsync/backends/gmail.py
In production we've seen this error come up before:
```
File "sync-engine/inbox/util/concurrency.py", line 73, in wrapped
return func(*args, **kwargs)
File "sync-engine/inbox/mailsync/backends/imap/monitor.py", line 174, in sync
self.start_new_folder_sync_engines()
File "sync-engine/inbox/mailsync/backends/imap/monitor.py", line 128, in start_new_folder_sync_engines
for folder_name in self.prepare_sync():
File "sync-engine/inbox/util/concurrency.py", line 73, in wrapped
return func(*args, **kwargs)
File "sync-engine/inbox/mailsync/backends/imap/monitor.py", line 52, in prepare_sync
sync_folders = crispin_client.sync_folders()
File "sync-engine/inbox/crispin.py", line 995, in sync_folders
to_sync.append(present_folders[folder][0])
IndexError: list index …
```
=> Check for "all" in foldernames before accessing it

.circleci/config.yml
This makes the CI process authenticate with Docker Hub in response
to the new rate limits starting in November.
=> Authenticate with Docker Hub

inbox/api/srv.py
Summary:
This changes allows users to set nylas's generic account SMTP settings without change the code. And also allows you(close.io settings) to use it with default settings if you don't send the smtp data.
=> Allow users to set nylas SMTP settings

Dockerfile, inbox/util/addr.py
When parsing long event descriptions (e.g. with a long base64 string), email detection can take a long time due to catastrophic backtracking (http://www.regular-expressions.info/catastrophic.html). We can speed this up without compromising on accuracy by limiting how much it backtracks. The email user part can be up to 64 chars and hostname part 255 chars.
=> Fix catastrophic backtracking when finding event emails

inbox/error_handling.py, inbox/transactions/actions.py
This provides a way for a user to filter out issues reported to Rollbar by specifying an environment variable `ROLLBAR_MESSAGE_FILTERS`. This environment carries a JSON string in form
```json
[
{"regex": "error regex 1", "threshold": 0.4},
{"regex": "error regex 2", "threshold": 0.00001},
...
]
```
Thresholds are probabilities of error matching given regex being reported. E.g. 0.5 means report 50% of times, 0 means never and greater or equal to 1 means always.
=> Filter out issues reported to Rollbar with given threshold

requirements_frozen.txt
It looks like the support for running tests in parallel has been long rotten.
If I try to enable xdist with 1 node I get:
```
============================ test session starts =============================
platform linux2 -- Python 2.7.12, pytest-2.8.3, py-1.5.2, pluggy-0.3.1
rootdir: /opt/app, inifile: 
plugins: xdist-1.13.1
gw0 okINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/venv/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/opt/venv/local/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File …
```
=> Remove pytest-xdist

requirements_frozen.txt, tests/imap/data.py, tests/security/test_blobstorage.py
This is the last version support Python 2.
It also solves this kind of DeprecationWarnings:
```
security/test_blobstorage.py::test_message_body_storage
security/test_blobstorage.py::test_encoded_format
security/test_blobstorage.py::test_blobstorage
/opt/venv/local/lib/python2.7/site-packages/hypothesis/core.py:517: HypothesisDeprecationWarning: Calling strategy with non-strategy object <type 'bool'> is deprecated and will be removed in Hypothesis 2.0. Use the functions in hypothesis.strategies instead.
return strategy(v.value, settings)
```
=> Upgrade hypothesis

.flake8, bin/inbox-start, inbox/crispin.py, inbox/util/misc.py, inbox/util/testutils.py, tests/imap/test_crispin_client.py
"\s" would be first escaped on a string level, but since there is no such \s escape it's just included as it is. This is error-prone. Use r"\s" or "\\s" instead.
=> Flake8: fix broken escapes

Dockerfile
Fixes: https://github.com/closeio/sync-engine/issues/72
```
❯ docker-compose run app wait-for-it.sh    
Creating sync-engine_app_run ... done
Error: you need to provide a host and port to test.
Usage:
wait-for-it.sh host:port [-s] [-t timeout] [-- command args]
-h HOST | --host=HOST       Host or IP under test
-p PORT | --port=PORT       TCP port under test
Alternatively, you specify the host and port as host:port
-s | --strict               Only execute subcommand if the test succeeds
-q | --quiet                Don't output any status messages
-t TIMEOUT | --timeout=TIMEOUT
Timeout in seconds, zero for no timeout
-- COMMAND ARGS             Execute command with args after the test finishes
```
=> wait-for-it.sh on PATH

requirements_frozen.txt
Currently we don't run pip check. This pull is a step towards running it.
Not satisfied constraint:
```
* astroid==1.6.1
- enum34 [required: >=1.1.3, installed: 1.0.4]
```
Changelog:
This project was versioned in hg (Mercurial) and hosted on Bitbucket that has since removed support for hg and deleted all the repos hosted there. I found a copy of the repo here: https://bitbucket-archive.softwareheritage.org/projects/st/stoneleaf/enum34.html
The project did not maintain a CHANGELOG file
The best I can do is `hg log`
```
2016-04-14 | Ethan Furman | version 1.1.3
2016-04-14 | Ethan Furman | Added tag 1.1.3 for changeset e5be6fbdf3e0
2016-04-14 | Ethan Furman | fix typo    1.1.3
2016-04-14 | Ethan Furman | add wheel support
2016-04-14 | Ethan Furman | add short long description
2016-04-14 | …
```
=> Upgrade enum34 to meet version constraints

requirements_frozen.txt
Currently we don't run pip check. This pull is a step towards running it.
Not satisfied constraint:
```
* gevent==1.1.2
- greenlet [required: >=0.4.9, installed: 0.4.2]
```
Changelog:
https://github.com/python-greenlet/greenlet/blob/master/CHANGES.rst?plain=1#L161-L206
Definitely should be deployed separately. Also contains some ARM fixes according to changelog.
=> Upgrade greenlet to meet version constraints

.circleci/config.yml, Dockerfile
Arm images are built on arm machine and with `-arm64` tag suffix.
Not running tests for arm - we don't do that for any of the other services as well.
=> Build arm image

inbox/instrumentation.py, requirements_frozen.txt, tests/test_instrumentation.py
https://pypi.org/project/psutil/
> psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
We are using it to monitor CPU times. The logic runs in a separate OS thread (that is not monkeypatched by gevent):
https://github.com/closeio/sync-engine/blob/b615cec56154209f3af525afd7d271b89fe2e33e/inbox/instrumentation.py#L121-L125)
Initialized here:
https://github.com/closeio/sync-engine/blob/b615cec56154209f3af525afd7d271b89fe2e33e/inbox/instrumentation.py#L106
Calculation done here:
https://github.com/closeio/sync-engine/blob/b615cec56154209f3af525afd7d271b89fe2e33e/inbox/instrumentation.py#L202-L209
This is the last version of psutil since it still works on …
=> Upgrade psutil and add tests for GreenletTracer

inbox/crispin.py, inbox/logging.py, inbox/util/concurrency.py
You want to use `.args[0]` which is forward and backward compatible.
=> BaseException.message is deprecated since 2.6 and removed in Python 3

inbox/search/backends/imap.py, tests/api/test_searching.py
This is about the internals of imaplib. When searching over an IMAP connection you are either supposed to send all the criteria items as `bytes` or all of them as `unicode`, but don't mix `bytes` with `unicode` at the same time.
This is better explained here:
https://github.com/mjs/imapclient/blob/1.0.0/imapclient/imapclient.py#L667-L717
=> Fix tests/api/test_searching.py

inbox/config.py, requirements_frozen.txt
Upgrades certificate store. This is the last verion that works on Python 2.7
=> Upgrade certifi

requirements_frozen.txt
Upgrade to a version explicitely tested on Python 3.6
Reverse dependencies:
```
cffi==1.14.6
- cryptography==2.1.4 [requires: cffi>=1.7]
- pyOpenSSL==17.5.0 [requires: cryptography>=2.1.4]
- gevent-openssl==1.2 [requires: pyOpenSSL>=0.11]
- IMAPClient==1.1.0a0 [requires: pyopenssl>=0.15.1]
- ndg-httpsclient==0.4.3 [requires: PyOpenSSL]
- nylas==1.2.3 [requires: ndg-httpsclient]
- nylas==1.2.3 [requires: pyOpenSSL]
- PyNaCl==0.3.0 [requires: cffi>=0.8]
```
Changelog
```
v1.14.6
Test fixes for CPython 3.10.0b3
Support for sys.unraisablehook() on Python >= 3.8
Fix two minor memory leaks (thanks Sebastian!)
Like many projects that had an IRC channel on freenode, we moved it to
irc.libera.chat.
v1.14.5
Source fix for old gcc versions
This and …
```
=> Upgrade cffi

requirements_frozen.txt
This is the last version of lxml and it still works on Python 2.
lxml is only used by contacts syncing which we don't use, updating for now nevertheless.
=> Upgrade lxml

inbox/instrumentation.py, inbox/mailsync/backends/imap/monitor.py, inbox/transactions/actions.py, requirements_frozen.txt
Greenlet and gevent need to be updated together since they closely depend on each other. Those are the last versions of greenlet and gevent, they still work on Python 2.
This needs to be deployed with care since sync-engine is built upon greenlet and gevent. I've been running these versions for a while locally and did not see any problems with them. I will be careful anyway.
Greenlet changelog:
```
1.1.2 (2021-09-29)
Fix a potential crash due to a reference counting error when Python subclasses of greenlet.greenlet were deallocated. The crash became more common on Python 3.10; on earlier versions, silent memory corruption could result. See issue 245. Patch by fygao-wish.
Fix a leak of a list object when the last reference to a greenlet was deleted from some other thread than the one to …
```
=> Upgrade gevent & greenlet

requirements_frozen.txt
Those two are not used through the code.
=> Remove simplejson & uritemplate

requirements_frozen.txt
=> Remove httplib2

requirements_frozen.txt
These are the latest versions of requests and urrlib3, they still work on Python 2.
We use requests to:
* talk to authalligator
* fetch Google calendar events
* fetch contacts (we don't use this feature)
I've tested those paths locally and everything is working.
Requests changelog
```
2.26.0 (2021-07-13)
Improvements
Requests now supports Brotli compression, if either the brotli or brotlicffi package is installed. (#5783)
Session.send now correctly resolves proxy configurations from both the Session and Request. Behavior now matches Session.request. (#5681)
Bugfixes
Fixed a race condition in zip extraction when using Requests in parallel from zip archive. (#5707)
Dependencies
Instead of chardet, use the MIT-licensed charset_normalizer for Python3 to remove license ambiguity for projects …
```
=> Upgrade requests and urllib3

requirements_frozen.txt
We use mysqlclient to talk to MySQL. This is the last version of mysqlclient that supports gevent. Support for gevent was removed in 1.4. For some historical reasons PyMySQL was also included in requirements but we no longer use it.
Changelog
```
Release: 2018-12-04
Support static linking of MariaDB Connector/C (#265)
Better converter for Decimal and Float (#267, #268, #273, #286)
Add Connection._get_native_connection for XTA project (#269)
Fix SEGV on MariaDB Connector/C when some methods of Connection objects are called after Connection.close() is called. (#270, #272, #276) See jira.mariadb.org/browse/CONC-289
Fix Connection.client_flag (#266)
Fix SSCursor may raise same exception twice (#282)
This removed Cursor._last_executed which was duplicate of Cursor._executed. Both members are …
```
=> Upgrade mysqlclient

etc/config-dev.json, requirements_frozen.txt
This is the latest version of PyNaCl, it still works on Python 2.
We use PyNaCl to cryptographically decode and encode blobs we store in S3. I've tested that blobs that are encoded on the old version can be decode on the new version and yield the same plaintext results and vice versa.
I've also enabled encode and decode for local development since this is what we actually do in production.
PyNaCl changelog
```
1.4.0 (2020-05-25)
Update libsodium to 1.0.18.
BACKWARDS INCOMPATIBLE: We no longer distribute 32-bit manylinux1 wheels. Continuing to produce them was a maintenance burden.
Added support for Python 3.8, and removed support for Python 3.4.
Add low level bindings for extracting the seed and the public key from crypto_sign_ed25519 secret key
Add low level bindings for deterministic …
```
=> Upgrade pynacl

requirements_frozen.txt
We use PyYAML to read the config which is stored in YAML. This is the last version that works on Python 2.
For some historical reason pyaml was also listed but we no longer use it.
PyYAML changelog:
```
5.4.1 (2021-01-20)
* https://github.com/yaml/pyyaml/pull/480 -- Fix stub compat with older pyyaml versions that may unwittingly load it
5.4 (2021-01-19)
* https://github.com/yaml/pyyaml/pull/407 -- Build modernization, remove distutils, fix metadata, build wheels, CI to GHA
* https://github.com/yaml/pyyaml/pull/472 -- Fix for CVE-2020-14343, moves arbitrary python tags to UnsafeLoader
* https://github.com/yaml/pyyaml/pull/441 -- Fix memory leak in implicit resolver setup
* https://github.com/yaml/pyyaml/pull/392 -- Fix py2 copy support for timezone objects
* …
```
=> Upgrade PyYAML

requirements_frozen.txt
Boto3 & botocore are only used in contacts sync which we don't use. Those are the latest versions that still work on Python 2.
=> Upgrade boto3 & botocore

requirements_frozen.txt
These are the last versions of tldextract and it's dependency idna that still work on Python 2.
We use tldextract to find parent domains of domains.
tldextract Changelog:
```
2.2.3 (2020-08-05)
Bugfixes
Fix concurrent access to cache file when using tldextract in multiple threads (#146)
Relocate version number, to avoid costly imports (#187)
Catch IndexError caused by upstream punycode bug (#200)
Drop support for EOL Python 3.4 (#186)
Explain warning better
2.2.2 (2019-10-15)
Bugfixes
Catch file not found
Use pkgutil instead of pkg_resources (#163)
Performance: avoid recomputes, a regex, and a partition
Misc.
Update LICENSE from GitHub template
Fix warning about literal comparison
Modernize testing (#177)
Use the latest pylint that works in Python 2
Appease pylint with the new rules …
```
=> Upgrade tldextract

requirements_frozen.txt
We use html2text to create text snippets from mails that don't contain text/plain part. This is the last version that works on Python 2.
Changelog
```
2019.8.11
Add support for wrapping list items.
Fix #201: handle &lrm;/&rlm; marks mid-text within stressed tags or right after stressed tags.
Feature #213: images_as_html config option to always generate an img html tag. preserves "height", "width" and "alt" if possible.
Remove support for end-of-life Pythons. Now requires Python 2.7 or 3.4+.
Remove support for retrieving HTML over the network.
Add __main__.py module to allow running the CLI using python -m html2text ....
Fix #238: correct spacing when a HTML entity follows a non-stressed tags which follow a stressed tag.
Remove unused or deprecated:
html2text.compat.escape() …
```
=> Upgrade html2text

requirements_frozen.txt
Before this pull request sync-engine used a fork of python-dateutil which contains following changes: https://github.com/dateutil/dateutil/compare/master...nylas:master. These changes change how `__str__` works in `dateutil.rrule.rrule` instances. I analyzed the code and we no longer call `str()` `__str__` etc on rrule instances. Thus the changes in the fork are no longer relevant. We instead use this function to serialize rrule to JSON:
https://github.com/closeio/sync-engine/blob/41b201ec99fd141e6e9a51c60a5d598424505637/inbox/events/recurring.py#L176-L197
The forked version is at 2.4.2. The new version is the latest version and it still works on Python 2.
Changelog
```
Version 2.8.2 (2021-07-08)
Data updates
Updated tzdata version to 2021a. (gh pr #1128)
Bugfixes
Fixed a bug in the …
```
=> Upgrade python-datetime

inbox/api/validation.py
This one is a little bit funny.
sync-engine does not allow `_` to appear in IDs. It uses `int(value, 36)` to validate them. But Python 3 allows numbers to contain underscores as thousand separators e.g. `8_000`.
```python
>>> int('invalid_id', 36)
File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 36: 'invalid_id'
>>> int('invalid_id', 36)
52650475151845
>>> 
```
=> Dont allow underscores in ids

inbox/sendmail/smtp/postel.py, tests/api/test_sending.py
`_substitue_bcc` is meant to work always on binary data. Changes nothing on Python 2 and fixes test on Python 3.
=> _subsitute_bcc operates on bytes

inbox/models/backends/generic.py, inbox/models/secret.py
Passwords are stored in MySQL in binary BLOB fields.
The logic already accepts bytes and text, and if it receives text it will encode it UTF-8 before saving.
On Python 3 the getters will return `bytes`. This is fine on Python 2 where it is a synonym of string and silently coerces to unicode in comparisons. But Python 3 needs an extra `.decode('utf-8')`.
=> Passwords are always text

requirements_frozen.txt
Upgrade hiredis. This is the last versiono that works on Python 3. redispy is already at the version that was tested on Python 3.6.
Changelog
```
1.1.0 (2020-07-15)
Allow "encoding" and "errors" attributes to be updated at runtime (see #96)
1.0.1 (2019-11-13)
Permit all allowed values of codec errors (see #86)
BUGFIX: READEME.md has UTF-8 characters, setup.py will fail on systems where the locale is not UTF-8. (see #89)
1.0.0 (2019-01-20)
(BREAKING CHANGE) Add ability to control how unicode decoding errors are handled (see #82)
Removed support for EOL Python 2.6, 3.2, and 3.3.
0.3.1 (2018-12-24)
Include test files in sdist tarball (see #80)
0.3.0 (2018-11-16)
Upgrade hiredis to 0.13.3
Add optional "shouldDecode" argument to Reader.gets() (see #77)
Add a "has_data" method to Reader objects …
```
=> Upgrade hiredis

tests/general/test_message_parsing.py
This one is funny. Flanker on Python 3 is better at guessing a charset so we can properly save an attachment in the mime used for this test. Given it contains emoji and emojis have a very special pattern that can be used reliability to guess encodings I am not surprised.
The multipart in question is:
```
From: Ben Bitdiddle <ben@example.com>
To: Helena Handbasket <helena@example.com>
Subject: The Monsters of MIME
Date: Thu, 30 Apr 2015 16:55:12 +0000
Content-Type: multipart/related; boundary="_004_143041291414210227nylascom_";
type="multipart/alternative"
MIME-Version: 1.0
--_004_143041291414210227nylascom_
Content-Disposition: attachment
EMPTY 😊
--_004_143041291414210227nylascom_
Content-Type: multipart/alternative;
boundary="_000_143041291414210227nylascom_" …
```
=> Fix multipart attachment encoding test on Python 3

inbox/api/validation.py, inbox/search/backends/imap.py, requirements_frozen.txt
This upgrades Flask & the dependencies to the latest versions that do not have too many breaking changes. This version of Flask is from February 2020 just before 1.0 happened. I will try to update past 1.0 on a separate PR in the future.
Flask-Restful was updated to the latest version.
Flask Changelog
```
Version 0.12.5
Released 2020-02-10
Pin Werkzeug to < 1.0.0. #3497
Version 0.12.4
Released 2018-04-29
Repackage 0.12.3 to fix package layout issue. #2728
Version 0.12.3
Released 2018-04-26
Request.get_json() no longer accepts arbitrary encodings. Incoming JSON should be encoded using UTF-8 per RFC 8259, but Flask will autodetect UTF-8, -16, or -32. #2692
Fix a Python warning about imports when using python -m flask. #2666
Fix a ValueError caused by invalid Range requests in some cases. …
```
=> Upgrade flask & friends

requirements_frozen.txt
This is the same version of imapclient we use in another project of ours.
The fixes we've made have been independently implemented upstream and are included in the latest release.
I've run manual email syncing tests with this version of imapclient.
=> Upgrade imapclient

inbox/models/backends/oauth.py, inbox/models/secret.py, tests/security/test_secret.py
This is very analogical to: https://github.com/closeio/sync-engine/pull/183
Refresh tokens are stored in MySQL in binary BLOB fields.
The logic already accepts bytes and text, and if it receives text it will encode it UTF-8 before saving.
On Python 3 the getters will return bytes. This is fine on Python 2 where it is a synonym of string and silently coerces to unicode in comparisons. But Python 3 needs an extra .decode('utf-8').
=> refresh_token is str

requirements_frozen.txt
Sync-engine uses icalendar to create ical files. This is the latest version of icalendar and it still works on Python 2. We don't use this feature.
icalendar changelog:
```
4.0.9 (2021-10-16)
Bug fixes:
Fix vCategories for correct en/de coding. [thet]
vDuration property value: Fix changing duration sign after multiple to_ical calls. Ref: #320 Fixes: #319 [barlik]
4.0.8 (2021-10-07)
Bug fixes:
Support added for Python 3.9 and 3.10 (no code changes needed).
Replace bare 'except:' with 'except Exception:' (#281)
4.0.7 (2020-09-07)
Bug fixes:
fixed rrule handling, re-enabled test_create_america_new_york()
4.0.6 (2020-05-06)
Bug fixes:
Use vText as default type, when convert recurrence definition to ical string. [kam193]
4.0.5 (2020-03-21)
Bug fixes:
Fixed a docs issue related to building on …
```
=> Upgrade icalendar

tests/contacts/test_remote_sync.py
gdata (https://pypi.org/project/gdata/) is not available on Python 3. This is the only test that fails because of it. Skip it for now.
We will most probably remove contact sync feature alltogether later. For the time being just skip it, as we don't use this code.
=> Skip contact test relying on gdata

tests/security/test_smtp_ssl.py
This test stopped working on Python 3.8. This is due to asyncore (https://docs.python.org/3/library/asyncore.html) and smtpd (https://docs.python.org/3/library/smtpd.html) being deprecated.
This test relies on asyncore and smtpd to start a dummy SMTP server with self signed certificate. One is supposed to rewrite it using asyncio and aiosmtpd (https://github.com/aio-libs/aiosmtpd) on latest Python versions. Given that we don't use email sending and will most probably get rid off e-mail sending from sync-engine it's not worth the effort right now.
=> Skip test_smtp_ssl_verification_bad_cert

inbox/crispin.py, inbox/mailsync/backends/imap/generic.py, inbox/util/testutils.py, tests/imap/data.py, tests/imap/test_delete_handling.py, tests/imap/test_folder_sync.py
This is a couple of str/bytes changes around the code that uses `CONDSTORE`.
`CONDSTORE` is a capability that allows the server to ask what messages changed in given folder since given `MODSEQ` (modification sequence). At least gmail supports it.
Modification sequences are monotonically increasing integers that server assigns to each message on change. If you ask the server for a `HIGESTMODSEQ` (highest modification sequence) in given folder, then sleep for a while, then `FETCH` messages since that highest modification sequence, you can implement efficient way to sync incremental changes, without `FETCH`ing all the messages from scratch.
=> CONDSTORE related bytes/str changes

Dockerfile, inbox/sendmail/smtp/postel.py
Newer versions of Python verify that the host we are conecting to matches the cert, one needs to provide host to the constructor, otherwise it wil fail.
We don't use this part of code (sending) but it was easy to fix anyway.
=> Fix SMTP host

inbox/sqlalchemy_ext/util.py
This is one of the small changes I need to start updating SQLAlchemy. That extra inheritance level from abc.ABCMeta adds not much value, but more importantly it breaks later versions of SQLAlchemy.
I was tempted to remove this abstract mixin all together but SQLAlchemy didn't like it. I might attempt it later after updating SQLAlchemy.
=> Simplify ABCMixin

requirements_frozen.txt
This is the last version of 2.x series and one of the first versions explicitly tested on Python 3.6.
sync-engine does not use MongoDB but...
sync-engine uses `bson.json_utils` and monkeypatches it to do serializing and deserializing of JSON that is stored in the database.
I did not discover why they are doing it but I guess it's safer that assume they had a reason. I might try to remove it altogether later when I am sure that it would not cause any problems.
Changelog
```
Changes in Version 2.9.5
Version 2.9.5 works around ssl module deprecations in Python 3.6, and expected future ssl module deprecations. It also fixes bugs found since the release of 2.9.4.
Use ssl.SSLContext and ssl.PROTOCOL_TLS_CLIENT when available.
Fixed a C extensions build issue when the interpreter was built with …
```
=> Upgrade pymongo

inbox/events/google.py, inbox/events/recurring.py, inbox/events/util.py, requirements_frozen.txt, tests/api/test_events_recurring.py
This upgrades arrow to the version that is explicitly tested on Python 3.8. 
sync-engine uses arrow to do all the date parsing handling, and also manipulation in many places.
I am trying to update it all the way to the last version supported on Python 2 but there are many breaking changes so I figured out I'd rather ship this in steps. There are two changes in this PR:
* use `shift` instead of `replace` when one means shift this date by X. arrow used to have one function to do both replacing and shifting (what a bad design)
* when parsing the dates and some component is out of range for example `0000-01-01` which means year zero it now raises `ValueError`
Changelog
```
0.14.7 (2019-09-04)
[CHANGE] ArrowParseWarning will no longer be printed on every call to arrow.get() with a datetime …
```
=> Upgrade arrow

Dockerfile, bin/contact-search-backfill.py, bin/contact-search-service.py, bin/inbox-api.py, bin/inbox-auth.py, bin/inbox-console.py, bin/inbox-start.py, bin/syncback-service.py, inbox/auth/utils.py, inbox/config.py, inbox/crispin.py, inbox/util/concurrency.py, requirements_frozen.txt, tests/conftest.py, tests/imap/test_pooling.py
This gates all the SSL fixes to make SSL decent on  Python 2 conditionally, we don't need them on Python 3 since they are already there in Python 3 ssl module.
Once we sunset Python 2 I am gonna remove all the Python 2 branches.
=> SSL changes for Python 3

.circleci/config.yml
Start pushing images for different Python versions so they can be tested conveniently. Also merges all the 4 build variants into one single build job that is parametrized now.
This PR has an accompanying PR in the other repository.
=> Push Python 3 images

inbox/auth/oauth.py
As written, on 3 one needs to look in args and if it's empty Python 2 would return `""` in message.
=> BaseException.message does not exist on Python 3

inbox/api/srv.py, inbox/mailsync/frontend.py
I've stumbled on mysterious
`TypeError: '<' not supported between instances of 'NoneType' and 'str'`
in `json.dumps` when manually testing things on Python 3.6.
It turns out Python 3.6 has a bug when one passes `sort_keys=True` into `json.dumps` and dictionaries have `None` keys and at least syncback uses such dictionaries. We don't pass it ourselves but we are using it indirectly with Flask's `jsonify`. I had to disable it on 3.6. We are going for 3.8 anyway so I think this is acceptable intermediate step.
See also: https://github.com/humanprotocol/hmt-escrow/issues/32
=> Disable JSON_SORT_KEYS

inbox/error_handling.py
This is the logic we use to artificially decimate the number of rollbars we get in production. Each exception messages is assigned a threshold to only report a percentage of the occurances.
There is a change between Python 2 & 3 on how exception data is stored in rollbar data. As Python 3 supports exception chains the whole chain is stored now elsewhere. This ensures that it works consistently between Python 2 & 3.
=> Rollbar and chains on Python 3

inbox/models/message.py
`quopri.decodestring` decodes quoted printable strings (https://en.wikipedia.org/wiki/Quoted-printable). 
Well formed quoted printable strings can only contain ASCII characetrs.
On Python 2 this function silently lets through invalid bytes with the highest bit set such as:
```
>>> quopri.decodestring("\xa0")
'\xa0'
>>> 
```
Python 3 since 3.3 checks the correctness:
```
>>> quopri.decodestring("\xa0")
ValueError: string argument should contain only ASCII characters
return a2b_qp(s, header=header)
```
Obviously email parts that claim to be quoted-printable and contain non ASCII are not well formed. We discussed what to do with this and we decided to discard such emails. On Python 2 we were previously saving them but this only shifted the problem …
=> Fix for quopri.decodestring raising errors on invalid characters in Python 3

requirements_frozen.txt
> WebOb provides objects for HTTP requests and responses.
WebOb is a dependency of flanker. This is the last version of WebOb and it still supports Python 2.7.
```
pipdeptree --reverse --packages WebOb
WebOb==1.8.7
- flanker==0.9.11 [requires: WebOb>=0.9.8]
```
WebOb only publishes changelog entries for minor releases, no micro releases changelogs
```
1.8.0
------------------
Feature
~~~~~~~
- ``request.POST`` now supports any requests with the appropriate
Content-Type. Allowing any HTTP method to access form encoded content,
including DELETE, PUT, and others. See
https://github.com/Pylons/webob/pull/352
Compatibility
~~~~~~~~~~~~~
- WebOb is no longer officially supported on Python 3.3 which was EOL'ed on
2017-09-29.
Backwards Incompatibilities
~~~~~~~~~~~~~~~~~~~~~~~~~~~
- Many changes …
```
=> Upgrade WebOb

inbox/crispin.py, inbox/mailsync/gc.py
Not related to Python 3 porting, just a problem we had before.
We are sporadically hitting errors when customers have labels in their Gmail inbox containing asterisks. Such us:
```
InvalidCriteriaError: b'Could not parse command'
``` 
For an IMAP search criteria like `["X-GM-LABELS", "*Asterisk"]`
This is an extension to IMAP by Google and we are using it. It also works differently than the rest of IMAP as implemented by `imapclient` library, specifically:
* the label has to be utf-7 encoded (https://en.wikipedia.org/wiki/UTF-7). This is documented here: https://developers.google.com/gmail/imap/imap-extensions 
* if the label contains asterisk it has to be quoted
We were already doing the first thing already but in the wrong place architecture-wise. 
About quoting ,`imapclient` only …
=> Gmail labels containing asterisks search fix

Dockerfile
This upgrades the base image from unsupported Ubuntu 16.04.7 LTS (Xenial Xerus) to Ubuntu 18.04.6 LTS (Bionic Beaver).
The default Python version on this image is Python 3.6.
I'm tracking 20.04 (Focal Fossa on a separate branch).
=> Ubuntu Bionic Beaver

requirements_frozen.txt
This contains mostly civil date DST changes etc.
```
release 2021c - 2021-10-01 14:21:49 -0700
Briefly:
Revert most 2021b changes to 'backward'.
Fix 'zic -b fat' bug in pre-1970 32-bit data.
Fix two Link line typos.
Distribute SECURITY file.
This release is intended as a bugfix release, to fix compatibility
problems and typos reported since 2021b was released.
Changes to Link directives
Revert almost all of 2021b's changes to the 'backward' file,
by moving Link directives back to where they were in 2021a.
Although 'zic' doesn't care which source file contains a Link
directive, some downstream uses ran into trouble with the move.
(Problem reported by Stephen Colebourne for Joda-Time.)
Fix typo that linked Atlantic/Jan_Mayen to the wrong location
(problem reported by Chris Walton).
Fix …
```
=> Upgrade pytz

requirements_frozen.txt
MarkupSafe is part of Flask.
Changelog
```
1.1.1
-------------
Released 2019-02-23
-   Fix segfault when ``__html__`` method raises an exception when using
the C speedups. The exception is now propagated correctly. :pr:`109`
1.1.0
-------------
Released 2018-11-05
-   Drop support for Python 2.6 and 3.3.
-   Build wheels for Linux, Mac, and Windows, allowing systems without
a compiler to take advantage of the C extension speedups. :pr:`104`
-   Use newer CPython API on Python 3, resulting in a 1.5x speedup.
:pr`64`
-   ``escape`` wraps ``__html__`` result in ``Markup``, consistent with
documented behavior. :pr:`69`
```
=> Upgrade MarkupSafe

requirements_frozen.txt
Starting upgrades to versions explicitly tested on Python 3.8. This is the last version of setproctitle.
For the time being I need to keep versions that work on Python 2.7 conditionally. I'll get rid off them once I get green light to ditch Python 2 support.
Changelog
```
1.2.2
-------------
- Fixed Windows build (issues 89, 90).
- Added wheel packages for Windows (issues 47, 90).
- Added wheel packages for aarch64 (issues 95).
1.2.1
-------------
- Fixed segfault after ``os.environ.clear()`` (issue 88).
1.2
~~~~~~~~~~~
- added ``getthreadtitle()`` and ``setthreadtitle()``.
- Initialisation of the module moved to the first usage: importing the module
doesn't cause side effects.
- Manage much longer command lines (52)
- Improved build on BSD, dropped ancient versions (issue 67).
- Fixed …
```
=> Upgrade setproctitle

inbox/models/event.py, inbox/sqlalchemy_ext/util.py
This marks type decorators as ready for SQLAlchemy query caching mechanism.
=> SQLAlchemy cache_ok

inbox/api/filtering.py, inbox/mailsync/backends/imap/common.py, inbox/models/account.py, inbox/models/folder.py, inbox/models/message.py, inbox/models/namespace.py, inbox/sqlalchemy_ext/util.py, inbox/transactions/delta_sync.py
The baked query extension is deprecated since 1.4:
https://docs.sqlalchemy.org/en/14/orm/extensions/baked.html
> Deprecated since version 1.4: SQLAlchemy 1.4 and 2.0 feature an all-new direct query caching system that removes the need for the BakedQuery system. Caching is now transparently active for all Core and ORM queries with no action taken by the user, using the system described at SQL Compilation Caching.
Since we will be updating to 1.4 we can get rid off it altogether.
=> Remove baked query

requirements/prod.txt
Upgrades to version tested on Python 3.8. It's also the last version. That needs to be conditional since it does not support Python 2.
Changelog
```
2.1.7
------------------
- support Python 3.9
- drop support for Python 3.5
2.1.6
------------------
- drop support for Python 2.7
- support Github Actions
- update dev-dependencies
2.1.5
------------------
- update language models (uchardet)
- add iso8859-2 test but disabled it
- support Python 3.8
- drop support for Python 3.4
2.1.4
------------------
- disable LTO because become poor performance
2.1.3
------------------
- support Python 3.7
2.1.2
------------------
- enable `LTO`_ for wheel builds
- update Cython
.. _LTO: https://gcc.gnu.org/wiki/LinkTimeOptimization
```
=> Upgrade cchardet

Dockerfile
This is the last version of pip. It only works on Python 3 so it's conditionally guarded until we drop Python 2.
=> Upgrade pip

inbox/util/testutils.py, tests/api/test_events.py, tests/api/test_metrics_api.py, tests/api/test_streaming.py, tests/conftest.py, tests/events/test_ics_parsing.py, tests/general/test_ignition.py, tests/general/test_message_parsing.py, tests/imap/test_actions.py, tests/pytest.ini, tests/scheduling/test_syncback_logic.py, tests/security/test_smtp_ssl.py, tests/system/test_events.py, tests/util/base.py
This addresses a couple of pytest warnings
`@yield_fixture` is a synonym of `@fixture` in moder pytest.
There were two markers, I documented `networkrequired` since it seems useful and removed `only` marker since I can't figure out what it was supposed to do.
=> pytest warnings

inbox/util/html.py, tests/general/test_html_parsing.py
This is a fix for a bug in Python 3's HTMLParser until Python 3.10. 
HTML can contain all the kinds of weird stuff and we were getting errors about `<![FOR]>`. We turn those errors into errors that the message processing pipeline understands and will not try to save HTML snippet for such emails.
https://bugs.python.org/issue31844
https://github.com/python/cpython/pull/8562/files#diff-7304624ffcc8be1268e5f86ebf1723034477694ce33456dc330f9c03f2d1e84f
=> HTMLParser handle unknown marked sections

requirements/prod.txt, requirements/test.txt
Changelog
```
1.1.0
-----
* Add support for `time.monotonic` (and `…_ns`)
* Allow to configure default ignore list, and also to just extend the default
* Fixed when accessing from thread after stop()
1.0.0
------
* Dropped Py2 support
* Added as_kwarg argument in order to have the frozen time object passed with the name pr
```
=> Upgrade freezegun

requirements/prod.txt
This is the last version that works on python 3.6
Changelog
6.0 series: https://ipython.readthedocs.io/en/stable/whatsnew/version6.html
7.0 series: https://ipython.readthedocs.io/en/stable/whatsnew/version7.html
=> Upgrade ipython

requirements/prod.txt
This is the last version of colorlog
Changelog
```
6.4.1
This breaks backwards compatibility in a few ways, most notably dropping support for Python versions older than 3.5. A warning will be displayed if you try to run it on an older version:
Colorlog requires Python 3.6 or above.
Pin 'colorlog<5' to your dependencies if you require compatibility with older versions of Python.
This lets colorlog drop some code that was getting very messy to maintain, which made adding and testing new features a slog. Other backwards incompatible changes have mostly been to internals, and some long requested features that have been a bit easier to add now.
Changes
Changes since [v6.3.0a1](https://github.com/borntyping/python-colorlog/releases/tag/v6.3.0a1).
- Renamed `colorlog.logging` to …
```
=> Upgrade colorlog 

requirements/prod.txt
Migrations still work, checked manually.
This is respectively the last version that works on 2.7, and the latest version.
Changelog
```
1.7.6
no release date
usecase
[usecase] [commands]
Add a new command alembic ensure_version, which will ensure that the Alembic version table is present in the target database, but does not alter its contents. Pull request courtesy Kai Mueller.
References: #964
bug
[bug] [autogenerate]
Implemented support for recognizing and rendering SQLAlchemy “variant” types going forward into SQLAlchemy 2.0, where the architecture of “variant” datatypes will be changing.
[bug] [autogenerate] [mysql]
Added a rule to the MySQL impl so that the translation between JSON / LONGTEXT is accommodated by autogenerate, treating LONGTEXT from the server as equivalent to an …
```
=> upgrade-alembic

inbox/sqlalchemy_ext/util.py, tests/test_sqlalchemy_ext.py
TLDR
Python 2.7
```
b'\xed\xa0\xbd'.decode('utf-8')
u'\ud83d'
```
Python 3.x
```
>>> b'\xed\xa0\xbd'.decode('utf-8')
File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
```
Python 3.x with surrogatepass
```
>>> b"\xed\xa0\xbd".decode('utf-8', 'surrogatepass')
'\ud83d'
```
Surrogate pairs is an alternative and deprecated way to encode characters that did not fit in original UTF-16 design. They use two separate unicode code points.
Some data that was saved in the database on Python 2 contained surrogate pairs and unpaired surrogate characters. This registers a codec that disallows encoding new surragate pairs but will gracefully decode data that contains surrogate pairs. It …
=> Fix surragate related errors on Python 3

.circleci/config.yml, Dockerfile, inbox/__init__.py, inbox/sendmail/base.py, inbox/sendmail/message.py, inbox/util/file.py, inbox/util/misc.py, inbox/util/testutils.py, setup.py, tests/general/test_message_parsing.py, tests/general/test_provider_resolution.py
before this PR when running something with docker you needed to stick `pip install -e .` because the code base relied on the fact that the package `inbox` is installed. This is annoying, especially when working with Docker and locally mounted volumes.
The code relied on `pkgutil.get_data()` to load fixture data and `pkgutil.get_modules()` to walk and import modules dynamically. I provided subtitues for those two that work without installing the module.
~~There were also VERSION constans read from setup.py in two places but those are not really needed for anything.~~
I inverted the logic about VERSION constant to read it from main `__init__.py` file, many Python packages do it this way.
Though this adds code, it also saves a lot of typing for everybody trying to run tests, ipython or …
=> Remove the need to pip install -e before executing commands

requirements/prod.txt
This is a backport. Python 2.7 only dep.
=> Gate simplegeneric on Python 3

inbox/contacts/processing.py
The underlying library sometimes parses name as a list. From the observations in Rollbar we know that the first element is the actual name and the second one is a title.
=> Fix for contact name being list

requirements/prod.txt
This is flanker dependency.
https://github.com/mrabarnett/mrab-regex does not provide a changelog or tags so ...
It's mostly extending stdlib re and adding new features only so it should be safe to do.
=> Upgrade regex

requirements/prod.txt
This is only used in contact sync feature that we don't use.
Changelog
```
1.19.4
======
* api-change:``emr-containers``: [``botocore``] This feature enables auto-generation of certificate  to secure the managed-endpoint and removes the need for customer provided certificate-arn during managed-endpoint setup.
* api-change:``chime-sdk-messaging``: [``botocore``] The Amazon Chime SDK now supports push notifications through Amazon Pinpoint
* api-change:``chime-sdk-identity``: [``botocore``] The Amazon Chime SDK now supports push notifications through Amazon Pinpoint
1.19.3
======
* api-change:``rds``: [``botocore``] This release adds support for Amazon RDS Custom, which is a new RDS management type that gives you full access to your database and operating system. For more information, see …
```
=> Upgrade boto3 on Python 3

inbox/scheduling/event_queue.py, tests/scheduling/test_event_queue.py
This caused a problem with initial sync in production. It boils down to de fact that `u"asd" != b"asd"` on Python 3 and `u"asd" == b"asd"` on Python 2 due to implicit coercion. Redis returns everything as binary both on Python 2 and Python 3.
I also added tests that used to fail on Python 3. 
```
=============================== FAILURES ================================
___________________________ test_event_queue ____________________________
def test_event_queue():
queue = EventQueue("name")
sent_event = {"event": "test"}
queue.send_event(sent_event)
received_event = queue.receive_event()
>       assert received_event.pop("queue_name") == queue.queue_name
E       AssertionError: assert b'name' == 'name'
E        +  where b'name' = <built-in method pop of dict object at …
```
=> Fix queue_name returned as bytes on Python 3

Dockerfile
When working on https://github.com/closeio/sync-engine/pull/250/files I forgot that we rely on the fact that those scripts end up on PATH when deploying.
=> Bring back pip install -e temporarily

inbox/__init__.py, inbox/actions/backends/__init__.py, inbox/contacts/__init__.py, inbox/events/__init__.py, inbox/events/actions/backends/__init__.py, inbox/mailsync/backends/__init__.py, inbox/models/__init__.py, inbox/models/backends/__init__.py, inbox/s3/__init__.py, inbox/s3/backends/__init__.py, inbox/search/backends/__init__.py, inbox/sendmail/__init__.py, inbox/util/__init__.py, inbox/util/misc.py, inbox/util/testutils.py, tests/__init__.py, tests/auth/__init__.py, tests/auth/providers/__init__.py, tests/providers/__init__.py
This was needed previously because `inbox` package was split between many root trees. With all the vendoring this is no longer needed.
=> Remove extend_path

.circleci/config.yml, inbox/util/concurrency.py
With all the code being syntactically correct Python 3 we can switch Flake8 to Python 3.
=> Flake8 on Python 3

inbox/scheduling/event_queue.py, tests/scheduling/test_event_queue.py
While canary testing this change I found out that I did not properly cover for the fact that queue_name can be already a string if `timeout is None`. As a result we got an exception on this line:
AttributeError: 'str' object has no attribute 'decode'
`queue_name = queue_name.decode("utf-8")`
I rewrote the logic slightly to make mypy happy. Note that I only ran mypy on this single file.
=> Fix the case where queue_name is already string because it did not arrive from Redis.

inbox/api/wsgi.py
This fixed RecursionError we had on Python 3 in gunicorn workers.
```
File \"/opt/venv/lib/python3.6/site-packages/flask/app.py\", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File \"/opt/venv/lib/python3.6/site-packages/flask/app.py\", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File \"/opt/app/inbox/api/ns_api.py\", line 640, in message_read_api
contents = get_raw_from_provider(message)
File \"/opt/app/inbox/s3/base.py\", line 4, in get_raw_from_provider
return account.get_raw_message_contents(message)
File \"/opt/app/inbox/models/backends/gmail.py\", line 108, in get_raw_message_contents
return get_gmail_raw_contents(message)
File \"/opt/app/inbox/s3/backends/gmail.py\", line 18, in …
```
=> Monkey patch early

requirements/prod.txt
This is Python 2 only dependency:
```
Python 2.7.17
configparser==4.0.2
- importlib-metadata==2.1.1 [requires: configparser>=3.5]
- pluggy==0.13.1 [requires: importlib-metadata>=0.12]
- pytest==4.6.11 [requires: pluggy>=0.12,<1.0]
- pytest-cov==2.12.1 [requires: pytest>=4.6]
- pytest-timeout==1.4.2 [requires: pytest>=3.6.0]
- pytest==4.6.11 [requires: importlib-metadata>=0.12]
- pytest-cov==2.12.1 [requires: pytest>=4.6]
- pytest-timeout==1.4.2 [requires: pytest>=3.6.0]
- SQLAlchemy==1.4.26 [requires: importlib-metadata]
- alembic==1.6.4 [requires: SQLAlchemy>=1.3.0]
```
```
Python 3.6.9
configparser==4.0.2
```
=> Gate configparser on Python 3.

requirements/prod.txt
Conditionally update cryptography to the latest possible versions on Python 2 and Python 3. The version we are currently using has a CVE assigned.
```
**SECURITY ISSUE:** Fixed a bug where certain sequences of ``update()`` calls
when symmetrically encrypting very large payloads (>2GB) could result in an
integer overflow, leading to buffer overflows. *CVE-2020-36242* **Update:**
This fix is a workaround for *CVE-2021-23840* in OpenSSL, fixed in OpenSSL
1.1.1j.
```
```
Python 2.7.17
cryptography==2.1.4
- pyOpenSSL==17.5.0 [requires: cryptography>=2.1.4]
- gevent-openssl==1.2 [requires: pyOpenSSL>=0.11]
- ndg-httpsclient==0.4.3 [requires: PyOpenSSL]
```
```
Python 3.6.9
cryptography==2.1.4
- flanker==0.9.11 [requires: …
```
=> Upgrade cryptography

requirements/prod.txt
> pycparser is a complete parser of the C language, written in pure Python using the PLY parsing library.
This is used in cffi and all libraries that depend on it.
```
Python 3.6.9
pycparser==2.18
- cffi==1.14.6 [requires: pycparser]
- cryptography==2.1.4 [requires: cffi>=1.7]
- PyNaCl==1.4.0 [requires: cffi>=1.4.1]
```
```
Python 2.7.17
pycparser==2.21
- cffi==1.14.6 [requires: pycparser]
- cryptography==2.1.4 [requires: cffi>=1.7]
- pyOpenSSL==17.5.0 [requires: cryptography>=2.1.4]
- gevent-openssl==1.2 [requires: pyOpenSSL>=0.11]
- ndg-httpsclient==0.4.3 [requires: PyOpenSSL]
- PyNaCl==1.4.0 [requires: cffi>=1.4.1]
```
changelog
```
+ Version 2.21 (2021.11.06)
- Much …
```
=> Upgrade pycparser

requirements/prod.txt
> Port of the 3.3+ ipaddress module to 2.6, 2.7, 3.2
```
Python 2.7.17
ipaddress==1.0.19
- cryptography==2.1.4 [requires: ipaddress]
- pyOpenSSL==17.5.0 [requires: cryptography>=2.1.4]
- gevent-openssl==1.2 [requires: pyOpenSSL>=0.11]
- ndg-httpsclient==0.4.3 [requires: PyOpenSSL]
```
Changelog
https://github.com/phihag/ipaddress/compare/v1.0.19...v1.0.23
=> Upgrade and gate ipaddress

requirements/prod.txt
This is Python 2 only dependency of ndg-httpsclient which is only needed on Python 2
```
Python 2.7.17
pyasn1==0.2.3
- ndg-httpsclient==0.4.3 [requires: pyasn1>=0.1.1]
```
=> Gate pyasn1

requirements/prod.txt, requirements/test.txt
> The pyparsing module is an alternative approach to creating and executing simple grammars, vs. the traditional lex/yacc approach, or the use of regular expressions.
This is also test only dependency
```
Python 2.7.17
pyparsing==2.4.7
- packaging==20.9 [requires: pyparsing>=2.0.2]
- pytest==4.6.11 [requires: packaging]
- pytest-cov==2.12.1 [requires: pytest>=4.6]
- pytest-timeout==1.4.2 [requires: pytest>=3.6.0]
```
```
Python 3.6.9
pyparsing==3.0.6
- packaging==20.9 [requires: pyparsing>=2.0.2]
- pytest==6.2.5 [requires: packaging]
- pytest-cov==3.0.0 [requires: pytest>=4.6]
- pytest-timeout==2.0.1 [requires: pytest>=5.0.0]
```
Changelog
```
3.0.6
---------------
- Added `suppress_warning()` method to individually suppress a warning on a
specific ParserElement. Used …
```
=> Upgrade pyparsing

requirements/prod.txt
> PLY is yet another implementation of lex and yacc for Python. Some notable features include the fact that its implemented entirely in Python and it uses LALR(1) parsing which is efficient and well suited for larger grammars.
```
Python 2.7.17
ply==3.10
- flanker==0.9.11 [requires: ply>=3.10]
```
```
Python 3.6.9
ply==3.11
- flanker==0.9.11 [requires: ply>=3.10]
```
Changelog
```
Ply
3.11
---------------------
02/15/18  beazley
Fixed some minor bugs related to re flags and token order.
Github pull requests 151 and 153.
02/15/18  beazley
Added a set_lexpos() method to grammar symbols.  Github issue 148.
04/13/17  beazley
Mostly minor bug fixes and small code cleanups.
```
=> Upgrade ply

requirements/prod.txt
Changelog
```
20.1.0
===================
- document WEB_CONCURRENCY is set by, at least, Heroku
- capture peername from accept: Avoid calls to getpeername by capturing the peer name returned by
accept
- log a warning when a worker was terminated due to a signal
- fix tornado usage with latest versions of Django
- add support for python -m gunicorn
- fix systemd socket activation example
- allows to set wsgi application in configg file using `wsgi_app`
- document `--timeout = 0`
- always close a connection when the number of requests exceeds the max requests
- Disable keepalive during graceful shutdown
- kill tasks in the gthread workers during upgrade
- fix latency in gevent worker when accepting new requests
- fix file watcher: handle errors when new worker reboot and ensure the list of …
```
=> Upgrade gunicorn

requirements/prod.txt
> structlog makes logging in Python faster, less painful, and more powerful by adding structure to your log entries. 
Changelog
```
21.4.0 (2021-11-25)
Backward-incompatible changes:
none
Deprecations:
none
Changes:
Fixed import when running in optimized mode (PYTHONOPTIMIZE=2 or python -OO). #373
Added the structlog.threadlocal.bound_threadlocal and structlog.contextvars.bound_contextvars decorator/context managers to temporarily bind key/value pairs to a thread-local and context-local context. #371
21.3.0 (2021-11-20)
Backward-incompatible changes:
structlog switched its packaging to flit. Users shouldn’t notice a difference, but (re-)packagers might.
Deprecations:
none
Changes:
structlog.dev.ConsoleRenderer now has sort_keys boolean parameter that allows to disable the sorting of keys …
```
=> Upgrade structlog

requirements/prod.txt
> Support for the Internationalised Domain Names in Applications (IDNA) protocol as specified in RFC 5891. This is the latest version of the protocol and is sometimes referred to as “IDNA 2008”.
```
Python 3.6.9
idna==2.9
- cryptography==2.1.4 [requires: idna>=2.1]
- flanker==0.9.11 [requires: idna>=2.5]
- requests==2.26.0 [requires: idna>=2.5,<4]
- authalligator-client==0.1 [requires: requests]
- requests-file==1.5.1 [requires: requests>=1.0.0]
- tldextract==2.2.3 [requires: requests-file>=1.4]
- rollbar==0.16.2 [requires: requests>=0.12.1]
- tldextract==2.2.3 [requires: requests>=2.1.0]
- tldextract==2.2.3 [requires: idna]
```
```
Python 2.7.17
idna==2.10
- cryptography==2.1.4 [requires: idna>=2.1]
- flanker==0.9.11 …
```
=> Upgrade idna

requirements/prod.txt
This project uses dns to lookup MX records etc. to guess IMAP and SMTP providers. We don't use that functionality ourselves.
Changelog for 2.x series
```
2.1.0
End-of-line comments are now associated with rdata when read from text. For backwards compatibility with prior versions of dnspython, they are only emitted in to_text() when requested.
Synchronous I/O is a bit more efficient, as we now try the I/O and only use poll() or select() if the I/O would block.
The resolver cache classes now offer basic hit and miss statistics, and the LRUCache can also provide hits for every cache key.
The resolver has a canonical_name() method.
There is now a registration mechanism for EDNS option types.
The default EDNS payload size has changed from 1280 to 1232.
The SVCB, HTTPS, and SMIMEA RR types are …
```
=> Upgrade dnspython

requirements/prod.txt
> attrs is the Python package that will bring back the joy of writing classes by relieving you from the drudgery of implementing object protocols .
Changelog
```
21.2.0 (2021-05-07)
Backward-incompatible Changes
We had to revert the recursive feature for attr.evolve() because it broke some use-cases – sorry! #806
Python 3.4 is now blocked using packaging metadata because attrs can’t be imported on it anymore. To ensure that 3.4 users can keep installing attrs easily, we will yank 21.1.0 from PyPI. This has no consequences if you pin attrs to 21.1.0. #807
21.1.0 (2021-05-06)
Deprecations
The long-awaited, much-talked-about, little-delivered import attrs is finally upon us!
Since the NG APIs have now been proclaimed stable, the next release of attrs will allow you to actually import attrs. …
```
=> Upgrade attrs

requirements/prod.txt
> Six is a Python 2 and 3 compatibility library.
Changelog:
```
1.16.0
------
- Pull request 343, issue 341, pull request 349: Port _SixMetaPathImporter to
Python 3.10.
1.15.0
------
- Pull request 331: Optimize `six.ensure_str` and `six.ensure_binary`.
1.14.0
------
- Issue 288, pull request 289: Add `six.assertNotRegex`.
- Issue 317: `six.moves._dummy_thread` now points to the `_thread` module on
Python 3.9+. Python 3.7 and later requires threading and deprecated the
`_dummy_thread` module.
- Issue 308, pull request 314: Remove support for Python 2.6 and Python 3.2.
- Issue 250, issue 165, pull request 251: `six.wraps` now ignores missing
attributes. This follows the Python 3.2+ standard library behavior.
1.13.0
------
- Issue 298, pull request 299: Add `six.moves.dbm_ndbm`.
- Issue …
```
=> Upgrade six

requirements/prod.txt
> This package supplies third-party access to the functionality of importlib.metadata including improvements added to subsequent Python versions.
```
Python 3.6.9
importlib-metadata==2.1.1
- alembic==1.7.5 [requires: importlib-metadata]
- pluggy==0.13.1 [requires: importlib-metadata>=0.12]
- pytest==6.2.5 [requires: pluggy>=0.12,<2.0]
- pytest-cov==3.0.0 [requires: pytest>=4.6]
- pytest-timeout==2.0.1 [requires: pytest>=5.0.0]
- pytest==6.2.5 [requires: importlib-metadata>=0.12]
- pytest-cov==3.0.0 [requires: pytest>=4.6]
- pytest-timeout==2.0.1 [requires: pytest>=5.0.0]
- SQLAlchemy==1.4.26 [requires: importlib-metadata]
- alembic==1.7.5 [requires: SQLAlchemy>=1.3.0]
```
```
Python 2.7.17
importlib-metadata==2.1.1
- pluggy==0.13.1 [requires: importlib-metadata>=0.12] …
```
=> Upgrade importlib-metadata

requirements/prod.txt
> Parses iCalendar and vCard files into Python data structures, decoding the relevant encodings. Also serializes vobject data structures to iCalendar, vCard, or (experimentally) hCalendar unicode strings.
Note that this is only used in contact import from iCloud, which we don't use ourselves.
Changelog
```
0.9.6
- Correctly order calendar properties before calendar components (98)
- Correctly serialize timestamp values (i.e. `REV`) (99)
- Pass correct formatting string to logger (102) - thanks CruzR!
- RRULE: Fix floating UNTIL with dateutil > 2.6.1 (115) - thanks Unrud!
- Encode params if necessary in serialization (109) - thanks matthias-k!
- Ignore escaped semi-colons in UNTIL value (114) - thanks Unrud!
- RRULE: Fix VTODO without DTSTART (116) - thanks Unrud!
- Fixed regexp for VCF …
```
=> Upgrade vobject

.circleci/config.yml
I've already started first production tests of Python 3.8 and will need ARM64 images soon.
=> Enable Python 3.8 on ARM64

inbox/util/html.py, tests/util/test_html.py
Out first Python 3.8 bug.
`cgi.escape` was deprecated since 3.2 (https://docs.python.org/3.7/library/cgi.html#cgi.escape) and was finally removed in 3.8.  One is suppoed to use `html.escape`. Note that there is a difference between `quote` param which is True by default in `html.escape`. We will be generating things that don't end up in HTML attributes so we can leave it set to False in both cases.
=> Fix plaintext2html

bin/check-attachments.py, bin/set-throttled.py, inbox/client/client.py, inbox/client/restful_models.py, inbox/crispin.py, inbox/models/util.py, inbox/scheduling/event_queue.py, inbox/sqlalchemy_ext/util.py, tests/api/test_event_when.py, tests/api/test_events.py, tests/auth/test_generic_auth.py, tests/imap/data.py
Note that those are not all unused imports in the code base. Some of them need more work because the code relies on import side effects.
=> Remove unused stdlib and 3rdparty imports

.github/workflows/build-and-release.yaml, .github/workflows/build-arm64.yaml
This was already dropped in CircleCI on master.
=> Drop Python 2.7 and 3.6 support from GHA

.circleci/config.yml, README.md, pytest.ini, tests/conftest.py
You can now run tests without specifying tests/ manually and also you do not need to pass env variable.
`docker-compose run app pytest` should be enough.
=> Simplify running tests

bin/get-object.py
I have removed unused obj variable by mistake during refactors, as you can see it's meant to be used in IPython console as a reference to the object you want to work on.
=> Fix get-object.py

inbox/console.py
Simplified .format() calls to fstrings in console.py now that program runs in Python 3.
=> replaced .format() with fstrings in console.py

Dockerfile
This upgrades the base image from Ubuntu 18.04 (Bionic Beaver) to current Ubuntu 20.04.3 LTS (Focal Fossa).
The default Python version on this image is Python 3.8.
=> Move to Focal Fossa

inbox/actions/backends/generic.py, inbox/actions/backends/gmail.py, inbox/api/ns_api.py
(Note that this is merging into https://github.com/closeio/sync-engine/pull/314.)
---
While reviewing [the other PR](https://github.com/closeio/sync-engine/pull/314), I thought that maybe the comments in some `try...except` clauses lost an important part of their meaning in translation: they look like they apply to the code in question unconditionally, instead of only when an exception is raised.
What I propose here is a notation to make it clear that that comment only applies if an exception covered by the `suppress` manager is raised:
```python
with suppress(AnException):
the_code_here()
```
What do you think?
=> Tweaks to how we document exceptions in suppress

requirements/prod.txt
This is the latest version from 7 series.
I tested manually if embedding IPython in the process works.
```
IPython 7.31¶
IPython 7.31 brings a couple of backports and fixes from the 8.0 branches, it is likely one of the last releases of the 7.x series, as 8.0 will probably be released between this release and what would have been 7.32.
Please test 8.0 beta/rc releases in addition to this release.
This Releases:
Backport some fixes for Python 3.10 (PR #13412)
use full-alpha transparency on dvipng rendered LaTeX (PR #13372)
Many thanks to all the contributors to this release. You can find all individual contributions to this milestone on github.
Thanks as well to the D. E. Shaw group for sponsoring work on IPython and related libraries.
IPython 7.30¶
IPython 7.30 fixes a couple of bugs …
```
=> Bump IPython to address CVE-2022-21699

requirements/prod.txt
This updates urllib3 to the latest version.
Changes include:
```
1.26.10 Latest
Removed support for Python 3.5
Fixed an issue where a ProxyError recommending configuring the proxy as HTTP instead of HTTPS could appear even when an HTTPS proxy wasn't configured.
1.26.9
Changed urllib3[brotli] extra to favor installing Brotli libraries that are still receiving updates like brotli and brotlicffi instead of brotlipy. This change does not impact behavior of urllib3, only which dependencies are installed.
Fixed a socket leaking when HTTPSConnection.connect() raises an exception.
Fixed server_hostname being forwarded from PoolManager to HTTPConnectionPool
when requesting an HTTP URL. Should only be forwarded when requesting an HTTPS URL.
1.26.8
Added extra message tourllib3.exceptions.ProxyError …
```
=> Update urllib3 to 1.26.10

.circleci/config.yml, Dockerfile, README.md, requirements/lint.txt
This will reduce maintenance effort required for keeping dependencies up to date and alert-free.
Note that new images are build without `-py3.x` suffix.
=> Only build with system-provided python 3.8

inbox/auth/oauth.py, inbox/client/client.py, inbox/client/restful_models.py, inbox/client/util.py
This is an artefact of Python 2 to 3 porting project. We are on Python 3 only now so we no longer need it.
=> Stop using six package

requirements/prod.txt
This is to clear a security alert:
Mako's changes:
https://github.com/sqlalchemy/mako/releases
I don't see anything concerning. The most impactful changes are related to Python 2 to 3 still, and dropping Python 3.6 support.
Tests pass locally.
=> Upgrade Mako to 1.2.2

inbox/events/ical.py, tests/events/test_ics_parsing.py
This is a problem I discovered when looking at the events in the database. This problem was introduced when I ported sync-engine from Python 2 to Python 3 and passed without being perceived. There's also a related Rollbar.
Events imported from ics provider (which means they were attachment files inside email messages) are wrongly serialized to the database with `b''` syntax i.e:
```sql
SELECT recurrence, rrule FROM event JOIN recurringevent r on r.id = event.id WHERE event.id = ******;
```
|recurrence|rrule|
|----------|-----|
|"RRULE:b'FREQ=DAILY;UNTIL=20220610T035959Z'"|RRULE:b'FREQ=DAILY;UNTIL=20220610T035959Z'|
recurrence field is supposed to contain Python serialized string, and rrule just the string itself.
This happens because `to_ical()` returns bytes that should be decoded before …
=> Fix bytes in event RRULE for ics provider

inbox/crispin.py
As discovered on one Outlook account you can get `None` as IMAP folder name, we cannot handle those so just skip them from syncing. The Outlook account in question has valid INBOX folder apart from malformed folder.
=> Filter out empty folder names

inbox/models/message.py
This currently causes Rollbars. We cannot force people not to send emails to too many people so it only makes sense to have a warning in server logs.
=> Recipient field too long warning

inbox/crispin.py, inbox/models/message.py, inbox/util/misc.py, tests/imap/test_crispin_client.py, tests/util/test_misc.py
We have a related rollbar.
This does two things:
* It checks we have absolutely minimal info on IMAP protocol level i.e. `FLAGS`, and `BODY[]` to actually recover a mail message. We cannot proceed without those. E.g. Microsoft likes to return deleted email message uids without `BODY[]`.
* It makes `INTERNALDATE` optional (it's always there on Gmail but not always there on Microsoft and generic IMAP). We already have logic in [inbox.models.message.Message._parse_metadata](https://github.com/closeio/sync-engine/blob/1f9a2e584d2f650c7bd8cc8e3f33103f47f68ed7/inbox/models/message.py#L421-L427) to recover it from parsed `BODY[]`.
=> Skip email messages without needed properties, recover from missing INTERNALDATE

inbox/crispin.py
These one creates very noisy rollbars.
There are IMAP accounts in the wild that really don't have INBOX folder (where you normally receive your incoming mail). I've examined some of those accounts and it's still worth syncing them because they have other folders (e.g. Sent) we could sync.
=> Don't explode on missing inbox folder

docker-compose.yml
While working on sync-engine I often drop to IPython shell, it would be tremendously useful to persist history.
=> Persist IPython history

.circleci/config.yml, inbox/models/when.py, requirements/lint.txt
This removes badly used `@abc.abstractproperty` that was used assigned on class properties instead of decorating instance properties. Mypy complains about it and also newer flake-bugbear will also say no.
=> Refactor When

inbox/events/timezones.py
These are some of the weird time zones you can find in ICS files generated by different Calendar software. I will keep updating this list based on common occurrences we have in  the wild but at some point when the occurrences drop below some threshold I will need to say it's enough and start rejecting them.
=> More timezones I saw in ICS files

inbox/models/message.py
At this point the message is not yet saved in the database so its public_id
will always be `None`. One needs to fetch it using IMAP instead to find out
what's wrong and `mid` is the IMAP uid.
=> Log IMAP uid when unknown Content-Disposition is discovered

inbox/auth/base.py
After investigating I confirmed that this happens only on generic IMAP (not Google or Microsoft) where customers maintain their own IMAP servers. The most common failure here is DNS expiring, but there are also timeouts. Given this is not our fault we should not Rollbar.
=> Warning on instantiating IMAP connection

inbox/models/message.py, tests/general/test_message_parsing.py
We cannot really recover from those two (completely screwed Mime encoding and too big message) so downgrade those to warnings.
=> Downgrade some parsing errors to warnings

inbox/api/kellogs.py, inbox/events/remote_sync.py, inbox/models/calendar.py, migrations/versions/254_add_calendar_default.py, tests/api/test_calendars.py, tests/conftest.py, tests/util/base.py
We need to know in sync-engine if your Calendar is default/primary or not. This is because when syncing we always start by syncing your default calendar as it's most likely the one you care about.
In case of Google you can know if a calendar is default/primary by comparing it's uid with account email address. In case of Microsoft calendar uids are opaque and Ms Graph API has dedicated default field that carries this information.
=> Microsoft: Extract is_default_calendar

inbox/events/google.py, inbox/events/remote_sync.py, inbox/models/backends/gmail.py, inbox/models/calendar.py, tests/webhooks/test_gpush_calendar_notifications.py
This changes `watch_calendar()` and `watch_calendar_list()` so they return `Optional[datetime.datetime]` instead of Google specific `Optional[int]` (where it meant UNIX timestamp in milliseconds). This will help sharing logic between Microsoft and Google.
=> Microsoft: Calendar.new_event_watch returns datetime.datetime

inbox/models/calendar.py, tests/api/test_calendars.py
While introducing `default` on Calendars to tell apart default and non default calendars
in calendar sync I forgot we have a special `inbox` Calendar for events created from ICS
files in mailbox. This is currently rollbaring.
=> Fix is_default_calendar for special 'inbox' calendars

inbox/models/backends/gmail.py, inbox/webhooks/gpush_notifications.py, tests/webhooks/test_gpush_calendar_notifications.py
These renames prepare webhook related fields to be shared between Microsoft and Google.
This only renames SQLAlchemy model properties and does not touch db columns.
The migration that actually renames the underlying database columns will follow on another PR.
=> Microsoft: Renames in Account model

inbox/models/calendar.py, migrations/versions/255_add_calendar_webhook_columns.py
This adds the final columns:
* `gpush_last_ping` -> `webhook_last_ping`
* `gpush_expiration` -> `webhook_subscription_expiration`
The columns are hidden behind Python property getter and setter. We write to both new and old column and when reading we prefer the newer column.
This will be followed by a PR that removes old columns.
=> Microsoft: Calendar model new columns

inbox/models/backends/calendar_sync_account.py, inbox/models/backends/gmail.py, migrations/versions/256_add_account_webhook_columns.py
This is similar to https://github.com/closeio/sync-engine/pull/408
This adds the final columns:
gpush_calendar_list_last_ping -> webhook_calendar_list_last_ping
gpush_calendar_list_expiration  -> webhook_calendar_list_expiration
The columns are hidden behind Python property getter and setter. We write to both new and old column and when reading we prefer the newer column.
This will be followed by a PR that removes old columns.
=> Microsoft: Account model new columns

inbox/models/backends/calendar_sync_account.py, migrations/versions/258_remove_account_old_webhook_columns.py
Stacked PR: Review [https://github.com/closeio/sync-engine/pull/411 first](https://github.com/closeio/sync-engine/pull/411), than review last 2 commits after ------ 8< ------
This drops the old columns.
=> Microsoft: Account model remove old webhook columns

inbox/events/google.py, tests/events/test_google_events.py
We extracted event ownership (`Event.owner`) info for Google Calendar events from `creator`, which doesn't change after transferring ownership. Oddly, we were computing `is_owner` from `organizer`, which is correct.
This PR uses `organizer` data to compute `owner`. In theory, it shouldn't be necessary to check `creator` (old behavior), but I left that check in case there's no `organizer` data (for some unknown reason).
https://github.com/closeio/sync-engine/blob/cdfdf6ab363cd2b17af9d5b0f745615c8fdc1f2a/inbox/events/google.py#L528-L536
=> Fix event ownership transfer for Google Calendar

inbox/api/metrics_api.py, tests/api/test_metrics_api.py, tests/util/base.py
Previously having a single account in a half broken state would lead to the whole `/metrics` giving 500. This is dangerous. Let's just skip accounts that for some reason cannot be serialized, but raise an error which will end up in Rollbar.
=> Don't explode metrics completely if one account is busted

inbox/api/srv.py, inbox/auth/google.py, inbox/auth/microsoft.py, tests/api/test_account.py
This adds an ability to turn on/off calendar_syncing in Microsoft accounts just like we currently do for Google accounts.
Note that in the payload we use `sync_calendars` where the actual field in the database is called `sync_events`. This is how we currently do that in Google as well.
=> Microsoft: Set sync_events in account creation/updates using API

inbox/events/google.py, inbox/events/microsoft/events_provider.py, inbox/events/microsoft/graph_types.py, inbox/events/remote_sync.py, inbox/mailsync/service.py, tests/events/microsoft/test_events_provider.py
This provides webhook support for events provider.
I also tested this end to end by deploying the image to a pod where my outlook sync is running. All looks good. In practice the time it takes to sync between me changing something in Outlook and CRM is less than 15 seconds with this PR.
=> Microsoft: Events provider webhook support

inbox/webhooks/microsoft_notifications.py, tests/webhooks/test_microsoft_notifications.py
This implements deletion of singular and recurring events (when entire series get cancelled).
This is implemented differently than in Google. In case of Google you can still fetch deleted events from  the API even though they disappear in your calendar. In case of Microsoft they disappear both from the API and calendar, so they cannot be fetched in sync pods and synced there, the only way we know something got deleted is in the webhook notifications.
This is not the cleanest approach from the architecture point of view but I want to [improve on this later](https://github.com/closeio/sync-engine/issues/425) after public release.
=> Microsoft: Cancel events

inbox/events/microsoft/events_provider.py, inbox/events/util.py, tests/events/microsoft/test_events_provider.py
This is implemented differently than in Google again. You cannot fetch deleted calendars with Microsoft (like we do in Google). We fetch them all anyway in each synchronization iteration and people typically have only a couple of calendars so one can just compare what comes from the API with what we have in the database.
=> Microsoft: Calendar deletes

inbox/events/microsoft/parse.py, tests/events/microsoft/test_parse.py
This is the part of the code responsible for converting Microsoft Graph event participant statuses to Google like event participant statuses. I forgot about `"organizer"` value which is documented here: https://learn.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0#properties and we have a Rollbar now.
=> Microsoft: Organizer attendee status

inbox/events/microsoft/graph_types.py, inbox/events/microsoft/parse.py, tests/events/microsoft/test_parse.py
While testing with real data I found that Microsoft Graph can return events with `"organizer"` set to `None`. We are rollbaring currently for those events.
=> Microsoft: Event organizer can be None

inbox/events/microsoft/graph_types.py, inbox/events/microsoft/parse.py, tests/events/microsoft/test_parse.py
Another Rollbar. We can have attendees without email addresses, we skip those in CRM.
=> Microsoft: Attendees without email addresses

inbox/events/microsoft/graph_types.py, inbox/events/microsoft/parse.py
Empirically from looking at user data Microsoft Graph can return null event subjects
and it makes CRM barf because it's not possible with Google. We try to mimick Google so let's
make it empty string.
=> Microsoft: null subjects

inbox/events/microsoft/graph_client.py, tests/events/microsoft/test_graph_client.py
As explained, now that we have people with substantial amount of events I could empirically see how far we can go with this to prevent rate limits on number of requests.
=> Microsoft: Rise page size for events

inbox/events/microsoft/graph_types.py, inbox/webhooks/microsoft_notifications.py, tests/webhooks/test_microsoft_notifications.py
Apart from the changes Microsoft delivers the information about subscription expiring over webhook and I did not realize that. We already renew them in sync pods and we can just ignore those but I need to ensure we don't Rollbar when we get those webhooks.
=> Microsoft: Handle subscription removed

inbox/webhooks/google_notifications.py, inbox/webhooks/microsoft_notifications.py
` OperationalError: (_mysql_exceptions.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') [SQL: UPDATE calendar SET updated_at=%s, webhook_last_ping=%s WHERE calendar.id = %s]`
Currently we are getting regular deadlocks inside API pods because Sync pods also do updates to calendar rows and they can currently run in parallel. This is only happening for Google but it could easily become problem with Outlook as well. The solution is to acquire EXCLUSIVE lock earlier in API as currently SELECT acquires SHARED lock and then we immediately do UPDATE (inside `handle_webhook_notification()`) which upgrades lock from SHARED to EXCLUSIVE and leads to deadlock with sync pods. Note that it means that transactions in API and sync pods around the same …
=> Use SELECT FOR UPDATE when updating calendar rows using API

inbox/transactions/actions.py
Something that was rollbaring since forever and I was scratching my head why.
The query in [here](https://github.com/closeio/sync-engine/blob/8fb0e4560b96bb574b62ed4a9249587198fef9ca/inbox/transactions/actions.py#L467-L476) always selects log entries from a single Namespace and Namespace to Account is 1 to 1 relation. So every log entry in the resultset belongs to the same account and would have the same `namespace.account_id`. But we were getting `AssertionError: account_id and namespace.account.id do not match`.
It was difficult to see but of course that's because we are comparing ints with `is` instead of `==`, and depending on where those are in memory it would raise or not. The fact that CPython interpreter tries to cache and reuse ints made this not so obvious as most of the time it …
=> Don't use is to compare ints

inbox/auth/generic.py, inbox/auth/oauth.py
These are caused by transient connection errors (not even authentication errors), I studied a lot of accounts that report those and they are syncing their email
just fine as we retry reconnection. There's no need for a Rollbar in those cases.
=> Demote connection errors to warnings

requirements/prod.txt
sync-engine uses `gevent` directly. `greenlet` is its dependency and needs to be updated at the same time.
gevent chanelog
```rst
22.10.2 (2022-10-31)
====================
Bugfixes
--------
- Update to greenlet 2.0. This fixes a deallocation issue that required
a change in greenlet's ABI. The design of greenlet 2.0 is intended to
prevent future fixes and enhancements from requiring an ABI change,
making it easier to update gevent and greenlet independently.
.. caution::
greenlet 2.0 requires a modern-ish C++ compiler. This may mean
certain older platforms are no longer supported.
See :issue:`1909`.
----
22.10.1 (2022-10-14)
====================
Features
--------
- Update bundled libuv to 1.44.2.
See :issue:`1913`.
Misc
----
- See :issue:`1898`., See :issue:`1910`., See :issue:`1915`.
---- …
```
=> Bump gevent & friends

inbox/mailsync/backends/imap/common.py, inbox/mailsync/backends/imap/generic.py
As noted [here ](https://github.com/closeio/sync-engine/blob/3fc0382512bba63e1a9fe551910c2a069b20615a/inbox/mailsync/backends/imap/generic.py#L540-L541) the imapuid can be already created due to race conditions, the logic already does the correct thing  in such case and there's no need to have an error here.
=> Demote expected to create imapuid

inbox/crispin.py
I looked at the occurrences and it practice it never meant that the folder was deleted. Things like connection lost, IMAP server shutting down and not accepting more commands, system errors. Anyway we retry next time so this is not worth a Rollbar.
=> Demote error selecting folder

inbox/events/abstract.py, inbox/events/google.py, inbox/events/microsoft/events_provider.py, inbox/events/remote_sync.py, tests/events/microsoft/test_events_provider.py
Sometimes calendar can be deleted between the point in time we see it in the calendar list and when we subscribe to changes in that calendar. If this happens with Microsoft we get a Rollbar currently. The code we already had handled it for Google by looking at the HTTP response code but you get different exceptions for Google and Microsoft. I've hidden both cases behind CalendarGoneException, as the code that handles this case should not be aware of the fact that providers use HTTP.
=> Microsoft: Calendar gone when subscribing

inbox/crispin.py, tests/imap/test_crispin_client.py
This is rollbaring for some accounts in production.
IMAP flags store additional metadata, like `b"\\Seen"` meaning that the email appears as opened in your mail program. Sometimes we get garbage flags that are integers, and this breaks code further down the road. We don't care about those and we can just filter them out.
=> Filter out bogus integer flags in GMail

.circleci/config.yml, docker-compose.yml
This is in preparation for Ubuntu 22.04. Note that this only changes the CircleCI runner image, and not Dockerfile for now.
=> Switch CircleCI runner to 22.04

inbox/events/microsoft/events_provider.py, inbox/events/remote_sync.py, tests/events/microsoft/test_events_provider.py
This is currently rollbaring for one account in production.
Sync-engine has two modes for syncing calendar:
* polling changes since last time it synced something, this has more delay of course 
* listening to webhooks, almost instant
Depending on what you return from ` webhook_notifications_enabled` it will do one of those two things.
For Microsoft I expected subscriptions to always work, but it turns out that it does not always work in practice. We can still fetch events and calendars but not create subscriptions in this case.
As explained in the docstring:
We found that in practice subscriptions don't work for some accounts. There are some theories on the internet why it does not work i.e.: Office365 administrator applying a restrictive policy or some weird setup when the calendars …
=> Microsoft: Probe if subscriptions work in webhook_notifications_enabled

inbox/api/ns_api.py
Sync-engine offers APIs that can return counts of the rows and row data.
When running `SELECT COUNT(*) FROM table WHERE ...` it normally does not make sense to add `ORDER BY` clauses since there is only one result. 
---
MySQL is lax on this and it will happily let you do it, even though it does not make sense:
```SQL
select COUNT(*) from 
(
SELECT 1 AS val
UNION ALL
SELECT 2 AS val
UNION ALL 
SELECT 3 AS val
) something ORDER BY val DESC;
```
| COUNT(*) |
| -------- |
| 3        |
---
but PostgreSQL will *rightly* complain, because you need `GROUP BY` to have more than one result and something to sort on:
```SQL
select COUNT(*) from 
(
SELECT 1 AS val
UNION ALL
SELECT 2 AS val
UNION ALL 
SELECT 3 AS val
) something ORDER BY val DESC;
```
`Query Error: error: column "something.val" must …
=> Don't ORDER BY when SELECT COUNT(*)

requirements/prod.txt
> 38.0.3 - 2022-11-01
>
> Updated Windows, macOS, and Linux wheels to be compiled with OpenSSL 3.0.7, which resolves CVE-2022-3602 and CVE-2022-3786.
Flanker uses cryptography to optionally [sign email messages](https://github.com/closeio/flanker-new/blob/63d1cdf927777f49f97e8d7f01e105a3b0d25cd2/docs/User%20Manual.md#dkim). We don't send emails from sync-engine so this should have no impact.
Bumped cffi at the same time as it's always backward compatible package.
Changelog
```rst
38.0.4 - 2022-11-27
Fixed compilation when using LibreSSL 3.6.0.
Fixed error when using py2app to build an application with a cryptography dependency.
38.0.3 - 2022-11-01
Updated Windows, macOS, and Linux wheels to be compiled with OpenSSL 3.0.7, which resolves CVE-2022-3602 and CVE-2022-3786.
38.0.2 - 2022-10-11 …
```
=> Bump cryptography

inbox/events/microsoft/events_provider.py, inbox/events/microsoft/graph_client.py, tests/events/microsoft/test_graph_client.py
This takes care of two things:
- When I changed `webhook_notifications_enabled` to create a dummy subscription and then delete it I did not realize this is called periodically in a loop. We need to do it only once to know if we are on unlucky account, then we can just cache it.
- We sporadically get `The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.`. We get this when subscribing to notifications over webhooks Microsoft makes an initial contact with webhook url. This is safe to retry.
=> Microsoft: handle sporadic underlying connection was closed, cache webhook_notifications_enabled

requirements/prod.txt
https://github.com/pypa/setuptools/issues/2352 which was the reason for pinning was resolved (and we also upgraded to Python 3.8 in the mean time)
=> remove pinned setuptools

inbox/events/google.py
This is rollbaring in production since forever.
Google workspace administrator can disable Google Calendars for specific user or entire workspace. We currently needlessly get 403 exceptions in this case. I also gave it a test drive on some production accounts and confirmed the rollbar is gone.
=> Google: not a calendar user

inbox/models/backends/oauth.py
Currently we get this error twice in Rollbar for every occurence: once for log.error
and another time when it reaches the bottom of the stack since it's reraised. We only need
it once.
=> Demote new token error log to warning

inbox/mailsync/backends/imap/common.py, inbox/models/account.py, inbox/models/backends/generic.py, inbox/models/backends/gmail.py, inbox/models/backends/imap.py, inbox/models/backends/outlook.py, tests/imap/test_update_metadata.py
This fixes the problem that for some accounts archived messages will randomly come back to inbox.
Long story short an IMAP message on generic (non-google) account can be only in a single folder. But for some of the on-prem IMAP servers (at least Dovecot according to my investigation) we are not able to reliably detect the fact that the message was moved from one folder to another (for example from inbox to archive) and it ends up in our database as if it was in those two folders at the same time (inbox, archive). This is never true in practice. I spent a lot of time trying to figure out why we cannot detect those moves, and we should keep investigating that but there's an intermittent solution that makes it easier on our customers.
The previous code would just select one of the folders, …
=> Make selecting categories for generic accounts deteministic.

inbox/crispin.py, tests/imap/test_crispin_client.py
The backstory:
One of our customers complained that "Done" button in email thread does not move their email to Archive folder. That button is supposed to mark the email as read and move it to Archive folder. It was only marking it as read.
The investigation:
I quickly found out that we are not able to identify Archive (Archiv in German) folder in German Outlook as it uses folder names in German. I was able to reproduce the same problem with outlook.de domain email myself. We assign roles to folders based on IMAP flags (think tags) and names. In case of Archive there are no standard IMAP flags so we do it by name but we don't take into account German name. This fixes it.
As always this is a gradual improvement as we cannot possibly know all the cases here. A lot of clients translate names …
=> Implement detection for German Archive folder

requirements/prod.txt
Changelog: https://ipython.readthedocs.io/en/stable/whatsnew/version8.html
Fixes a CVE but apparently it's only exploitable on Windows.
Bumped all the packages down the tree at the same time.
```
ipython==8.10.0
- backcall [required: Any, installed: 0.2.0]
- decorator [required: Any, installed: 5.1.0]
- jedi [required: >=0.16, installed: 0.18.1]
- parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
- matplotlib-inline [required: Any, installed: 0.1.3]
- traitlets [required: Any, installed: 5.9.0]
- pexpect [required: >4.3, installed: 4.8.0]
- ptyprocess [required: >=0.5, installed: 0.7.0]
- pickleshare [required: Any, installed: 0.7.5]
- prompt-toolkit [required: >=3.0.30,<3.1.0, installed: 3.0.36]
- wcwidth [required: Any, installed: 0.2.5]
- pygments [required: >=2.4.0, installed: …
```
=> Bump ipython to 8.10.0

requirements/prod.txt
Bumps cryptography because of CVE
We don't use crptography directly
```
cryptography==36.0.0
```
Flanker itself [only uses cryptogtaphy to do DKIM](https://github.com/mailgun/flanker/blob/2bb021ee48dd3aebe7bf2aac098df61d55fc299b/flanker/dkim.py) which concerns email sending and we don't send emails from sync-engine.
Changelog
```
.. _v39-0-1:
39.0.1 - 2023-02-07
~~~~~~~~~~~~~~~~~~~
* **SECURITY ISSUE** - Fixed a bug where ``Cipher.update_into`` accepted Python
buffer protocol objects, but allowed immutable buffers. **CVE-2023-23931**
* Updated Windows, macOS, and Linux wheels to be compiled with OpenSSL 3.0.8.
.. _v39-0-0:
39.0.0 - 2023-01-01
~~~~~~~~~~~~~~~~~~~
* **BACKWARDS INCOMPATIBLE:** Support for OpenSSL 1.1.0 has …
```
=> Bump cryptography to 39.0.1

inbox/webhooks/microsoft_notifications.py, requirements/prod.txt, tests/webhooks/test_microsoft_notifications.py
Note that Flask is already at 2.2.x, I'm upgrading minimally to have a version of Werkzeug that does not have [CVE](https://security.snyk.io/vuln/SNYK-PYTHON-WERKZEUG-3319936)
Also we don't use Jinja, itsdangerous or MarkupSafe in sync-engine.
I tested email sync, sync back and calendar sync extensively manually both locally and on one production cluster.
The only thing that broke is how Flask handles `request.json` without `Content-Type: application/json`
Flask changelog
```
Version 2.0.3
-------------
Released 2022-02-14
-   The test client's ``as_tuple`` parameter is deprecated and will be
removed in Werkzeug 2.1. It is now also deprecated in Flask, to be
removed in Flask 2.1, while remaining compatible with both in
2.0.x. Use ``response.request.environ`` instead. :pr:`4341`
-   Fix …
```
=> Upgrade Flask to 2.0.3

requirements/prod.txt
Always good idea to keep this on the latest micro version as sync-engine is all built around gevent and greenlet. Gevent did not have any release.
Changelog:
```
2.0.2 (2023-01-28)
==================
- Fix calling ``greenlet.settrace()`` with the same tracer object that
was currently active. See `issue 332
<https://github.com/python-greenlet/greenlet/issues/332>`_.
- Various compilation and standards conformance fixes. See #335, #336,
#300, #302, #334.
```
=> Upgrade greenlet

inbox/events/microsoft/parse.py, tests/events/microsoft/test_parse.py
Fixes #
Summary:
MSGraph can return values such as `{"dateTime": "0001-01-01T00:00:00.0000000Z", "timeZone": "tzone://Microsoft/Utc"}` for some calendar events' `start` or `end` fields. This causes `tzinfo.localize(dt)` in `parse_msgraph_datetime_tz_as_utc` to fail, as `tzinfo` is already set.
Test Plan:
Reviewers:
Please add the reviewer as an assignee to this PR on the right
=> Handle MSGraph timezone-aware datetimes

inbox/models/thread.py
This is a stop gap solution for https://github.com/closeio/sync-engine/issues/302.
There's a pretty laud rollbar both on CRM and sync-engine side.
`category` can be None because somebody at Nylas decided to drop a foreign key mentioned in [the issue](https://github.com/closeio/sync-engine/issues/302). We should still investigate if we can add those constraints back because the decision to drop such constraints does not look like a correct one to me. In the meantime let's ship this because for people that hit this problem we simply get stuck on this and stop syncing their inboxes.
=> Don't break on missing categories

inbox/models/message.py
TLDR: we had an email message in our production cluster that was causing OOMs while being synced. I downloaded the message, measured memory pressure while parsing it and realized that email prasing logic uses excessive amount of RAM and does pointless operations. 
1. We do pointless `str` -> `bytes` -> `str` conversions while storing html and text parts, we just need `str`s.
2. While calculating message snippet and body we always prefer html parts over plain parts. Most emails these days contain alternative html and plain parts, the plain parts are only carried for the reason of backwards compatibility. Nonetheless we were carrying over plain parts through processing and doing calculations on it even if we were throwing away the results.
3. We were prematurely decoding a mimepart by …
=> Reduce mail parsing memory footprint, don't do useless processing

inbox/mailsync/service.py, tests/scheduling/test_sync_start_logic.py
- removed unnecessary passing of `event` parameter into `poll()`
- renamed `poll_shared_queue` into `handle_shared_queue_event` to better describe what the function actually does
=> Clean up sync code related to event queues

inbox/models/message.py, inbox/util/addr.py, tests/general/test_message_parsing.py
This prevents following situation we are currently facing with a particular inbox.
The inbox has garbled email messages in it. Some of them are garbled inside address headers leading the parser to try interpreting garbage as a very long email names/address. It eventually leads to out of memory and crash entire sync worker :-) This introduces a hard limit on header length which is what MySQL's maximum on TEXT field (65 KB) which is the type we use to store email addresses. Such messages are garbage anyway so we just mark them as invalid and move on.
=> Validate address headers earlier to prevent OOM

Dockerfile, requirements/prod.txt
Resolves [CVE-2022-40897](https://github.com/advisories/GHSA-r9hx-vwmv-q579)
We need to bump PyMongo along with setuptools, because bumping setuptools removes 2to3 that PyMongo's installation depends on.
Changelog: https://pymongo.readthedocs.io/en/stable/changelog.html
Since we only use `bson.json_util`, the part that should interest us is this:
https://user-images.githubusercontent.com/113755748/231822387-e2bf782c-4c64-4550-abd0-9a972c58a26a.png
It looks like these changes do not affect us, but I'm not sure about the `Int64` bit.
Also, not 100% sure I understand why we're using the PyMongo bson module.
Is it so that we can store arbitrary data structures (including datetimes) in the database using a string representation of BSON?
=> Bump setuptools to 67.4.0 and pymongo to 3.0

inbox/crispin.py, tests/imap/test_crispin_client.py
Fixes: https://github.com/closeio/sync-engine/issues/485
=> Allow parse_message_list to gracefully handle many elements

inbox/mailsync/service.py
Currently we're [polling the database](https://github.com/closeio/sync-engine/blob/master/inbox/mailsync/service.py#L135) on *every* loop iteration so listening to the Redis queue for events only means we'll start syncing the new account(s) sooner than in 20s which is what the poll interval is set to.
I think the call that I moved was intended to be _outside_ the worker loop so we'd only poll the state of the world on startup and then rely on EventQueue to start syncing new accounts.
WDYT @squeaky-pl  ? I'm not sure if this is worth merging since I don't see this polling to be a significant load on the DB.
=> move initial poll call out of loop

inbox/mailsync/service.py
This reverts commit 570077052332f6a8d10e58741d1e66da3fb50e42.
New accounts aren't assigned if this patch is included.
=> Revert "move initial poll call out of loop (#479)"

requirements/prod.txt
Sorts out CVE mentioned at the top in the changelog. The only incompatible changes are related to dropping support for old Python versions.
Changelog
```
2.31.0 (2023-05-22)
-------------------
**Security**
- Versions of Requests between v2.3.0 and v2.30.0 are vulnerable to potential
forwarding of `Proxy-Authorization` headers to destination servers when
following HTTPS redirects.
When proxies are defined with user info (https://user:pass@proxy:8080), Requests
will construct a `Proxy-Authorization` header that is attached to the request to
authenticate with the proxy.
In cases where Requests receives a redirect response, it previously reattached
the `Proxy-Authorization` header incorrectly, resulting in the value being
sent through the tunneled connection to the destination server. Users …
```
=> Upgrade requests and friends

inbox/api/kellogs.py, inbox/events/google.py, inbox/models/event.py, migrations/versions/260_add_event_conference_data.py, tests/events/test_google_events.py
To correctly support Zoom and possible other add-ons that you can install into your Google workspace we need to expose Google's `conferenceData` that contains Zoom related data. Zoom add-on does not add anything to event description or location.
To follow previous sync-engine conventions I use `snake_case` instead of `camelCase`. I also only exposed a subset we need i.e. URIs and conference solution name as we don't immediately need all this data and I don't want to needlessly store it in a table that is quite large already. I normally would not want to expose JSON columns but we already do this in sync-engine and if we ever need to support more add-ons and more data it's gonna be easier (every migration needs to be ran across many databases).
Note that I [explicitly validate the JSON …
=> Expose Google conferenceData

inbox/config.py, inbox/mailsync/service.py
Sync-engine has two classes for calendar syncing:
- `EventSync` - poll calendar changes
- `WebhookEventSync` - rely on webhooks to detect calendar changes
both Google and Microsoft providers support both.
When working locally you always want to run event syncing using polling, otherwise you are unable to receive calendar changes (unless you set up some webhook tunnel). Historically I've been always editing code locally to run `EventSync` classes instead of `WebhookEventSync` but I got tired of doing it. I've dried up the event syncing greenlets into `start_evet_sync` method.
Until recently we only had Google event sync so the `FEATURE_FLAGS` switch was called `GOOGLE_PUSH_NOTIFICATIONS` which is also confusing because at least I think of mobile push notifications when I hear push …
=> Allow running sync locally without webhooks

requirements/prod.txt
Changelog
```
23.7.0 (2023-07-11)
===================
Features
--------
- Add preliminary support for Python 3.12, using greenlet 3.0a1. This
is somewhat tricky to build from source at this time, and there is
one known issue: On Python 3.12b3, dumping tracebacks of greenlets
is not available.
:issue:`1969`.
- Update the bundled c-ares version to 1.19.1.
See :issue:`1947`.
Bugfixes
--------
- Fix an edge case connecting a non-blocking ``SSLSocket`` that could result
in an AttributeError. In a change to match the standard library,
calling ``sock.connect_ex()`` on a subclass of ``socket`` no longer
calls the subclass's ``connect`` method.
Initial fix by Priyankar Jain.
See :issue:`1932`.
- Make gevent's ``FileObjectThread`` (mostly used on Windows) implement
``readinto`` cooperatively. PR by …
```
=> Upgrade gevent

inbox/logging.py, tests/test_logging.py
`create_error_log_context` is used to enrich logs with exception information. Sometimes we get a pretty long messages containing several MBs of data. This happens often with IMAP errors when servers returns some type of garbage we cannot parse as imaplib will include entire response in the exception args. This in turn needlessly stresses our logging infra.
=> Limit error_message length

inbox/events/microsoft/parse.py, tests/events/microsoft/test_parse.py
Note that we won't sync this to CRM because I've only seen this on events that have this in body
```
'start': {'dateTime': '9999-12-31T23:59:59.9999999', 'timeZone': 'UTC'},
'end': {'dateTime': '9999-12-31T23:59:59.9999999', 'timeZone': 'UTC'},
```
and we don't sync events with `start == end` to CRM.
=> Truncate datetimes that cannot be saved in MySQL

inbox/crispin.py, inbox/models/backends/imap.py
imaplib parses IMAP responses based on regular expression patterns. If something looks like integer e.g. `"123"` it will be returned as integer `123` to client code and if something looks like string e.g. `"asd"` it will be returned as bytes `b"asd"`.
In general IMAP servers should not mix things that look like strings with things that look like like ints but some IMAP servers (we have at least two different accounts with rollbars) do it. I am pretty sure that int flags are not even valid but couldn't find anything anything in the spec to support this claim. (Flags normally start with \ or $ character which would guarantee the to be bytes).  Nonetheless we don't care about int flags as they are definitely non-standard and we don't know how to interpret them.
The end result here is that if …
=> convert_flags

inbox/events/microsoft/graph_types.py, inbox/events/microsoft/parse.py, tests/events/microsoft/test_parse.py
Normally a body is a dictionary that looks like this `{"contentType": "html", "content": "..."}`.
It should not be nullable (at least according to Microsoft) but our experience with Rollbars shows otherwise. Not the first time Microsoft contradicts themselves.
=> Correctly handle None event body for Microsoft calendars

requirements/prod.txt
Summary:
Updating Flask to address CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-30861
Test Plan:
Tested via automated tests, will need advice for relevant manual testing.
=> Bump flask version

inbox/models/event.py, tests/events/test_create_and_update.py
Back when implementing https://github.com/closeio/sync-engine/pull/491 I forgot about the fact that sync engine always creates transient objects even when doing updates.
i.e. when it updates event objects it does something like that `persistent_event.update(transient_event)`. Every time you add a new column you are supposed to update `.update()`. That means that changes to `conference_data` were never synced after initial event creation.
=> Fix conference_data not being populated on event updates

requirements/prod.txt
Looks like all the changes are backward-compatible or bugfixes.
=> Bump gevent to `23.9.1` to resolve `CVE-2023-41419`

inbox/instrumentation.py
This may mean that the entire pod gets stalled eventually and should have more visibility in Rollbar
=> Make the fact that something is being killed an error

inbox/api/ns_api.py, tests/imap/data.py
[Docs](https://flask.palletsprojects.com/en/3.0.x/api/#flask.send_file).
We should not be encoding those headers manually, instead let Flask do its thing.
Given this code was written more than 10 years ago it does not surprise me the way it was done originally back then.
=> Use send_file to create file download response

Dockerfile
Needed to bump urllib3 version bundled inside pip as it has these [CVEs](https://security.snyk.io/package/pip/urllib3/1.26.14) 
Changelog:
```
23.3.1 (2023-10-21)
Bug Fixes
Handle a timezone indicator of Z when parsing dates in the self check. ([#12338](https://github.com/pypa/pip/issues/12338))
Fix bug where installing the same package at the same time with multiple pip processes could fail. ([#12361](https://github.com/pypa/pip/issues/12361))
23.3 (2023-10-15)
Process
Added reference to [vulnerability reporting guidelines](https://www.python.org/dev/security/) to pip’s security policy.
Deprecations and Removals
Drop a fallback to using SecureTransport on macOS. It was useful when pip detected OpenSSL older than 1.0.1, but the current pip does not support any Python version supporting …
```
=> Upgrdade pip

inbox/webhooks/google_notifications.py, tests/webhooks/test_gpush_calendar_notifications.py
Adds a throttle to `/calendar_list_update/<account_public_id>`.
Google allows you to subscribe to the same resource many times. The Google subscription logic in nyls-sync is kind of dumb. It will create a new subscription each time the calendar sync greenlet starts. If for whatever reason it's restarted too many times in short period of time we would indirectly DDOS ourselves by Google, as it will deliver as many notifications for a single change as many times we subscribed.
This how such incident looks like:
And then it will trickle down to mysql problems
This puts an RPS band-aid we already had in the other endpoint `/calendar_update/<calendar_public_id>`.
This will hopefully keep it from alerting us during Xmas break 🎅.
Long-term we should really ensure that we check in nylas-sync that …
=> Add throttle to /calendar_list_update/<account_public_id>

inbox/events/remote_sync.py
[Response](https://requests.readthedocs.io/en/latest/_modules/requests/models/#Response) class has a `__bool__` that delegates to `.ok` - so it's not suitable for nullability check. This PR use an actual nullability check.
Issue Introduced in https://github.com/closeio/sync-engine/commit/940fe5a44ecc21fac0fbc4d298850ffb5431b24d#diff-8eac2193636c772e0f91e1271b85a19ace467179c8d9743e078dc071f13158cdR361
Fixes https://app.rollbar.com/a/ElasticInc/fix/item/sync-engine/1340
=> Fix 404 response status check on calendar sync

inbox/events/google.py
Another `Response.__bool__` footgun that delegates to `.ok` similar to https://github.com/closeio/sync-engine/pull/630
Fixes https://app.rollbar.com/a/ElasticInc/fix/item/sync-engine/1343
Related to https://github.com/closeio/sync-engine/commit/f2263e7478db22c3874a04cecb82670f1873d87a (cc @gcheshkov)
=> Fix 410 response status check on calendar sync

inbox/events/google.py
Google will soon start returning other event types in their APIs that we don't care about. This change ensures that everything keeps working as before.
https://developers.google.com/calendar/api/v3/reference/events/list
```
eventTypes 	string 	Event types to return. Optional. This parameter can be repeated multiple times to return events of different types. The default is ["default", "focusTime", "outOfOffice"].
Acceptable values are:
"default": Regular events.
"focusTime": Focus time events.
"outOfOffice": Out of office events.
"workingLocation": Working location events.
```
=> Google: Pass eventTypes

inbox/events/google.py, inbox/events/microsoft/events_provider.py, inbox/util/concurrency.py
Normally these loops parse a very limited number of events, but at the initial sync the implementation will fetch all the events into a list and then start parsing them all. This might block the loop for a little too long and result in the calendar syncing greenlet being interrupted and killed.
=> Events: Periodically switch out of the event parsing loop

inbox/events/google.py
Originally in https://github.com/closeio/sync-engine/pull/664 we starting passing `eventTypes`. Today when I was doing unrelated changes I realized that the changes aren't arriving close to realtime and the webhooks about changes in the calendar are not delivered anymore. I think Google jinxed themselves and the webhooks API is not working correctly with their new APIs.
Through several manual tests I confirmed that fetching the events works while filtering with `eventTypes`, but webhooks are not delivered (although the subscription is created successfully) with the new parameter.
The rest of the logic will keep working as expected because we only update a timestamp in the database in the API pods, and then in the SYNC pods we fetch changes between the time we last synced and that …
=> Revert subscription eventTypes change

inbox/heartbeat/store.py, inbox/models/transaction.py, requirements/prod.txt, tests/util/base.py
Closes #481 
Upgrades the redis-py library to 5.0.2.  
This also upgrades hiredis to the latest version.
A few usage changes were required due to a breaking API change for `zadd`:
>  * ZADD now requires all element names/scores be specified in a single dictionary argument named mapping. This was required to allow the NX, XX, CH and INCR options to be specified.
We're still using the `mockredis` package to mock redis calls, but that hasn't been updated. I added a patch to translate to the old API still used by `mockredis`.
=> Upgrade redis-py to 5.0.2

Dockerfile
Not that we install anything using Mercurial so we are not affected really. Bumped both to the latest version because those are safe updates.
=> Upgrade pip & virtualenv

requirements/prod.txt
From dependabot alert: https://github.com/closeio/sync-engine/security/dependabot/44
=> Upgrade gunicorn 20.1.0 -> 22.0.0

requirements/prod.txt
Upgrade werkzeug
Changelog
```
Version 3.0.3
-------------
Released 2024-05-05
-   Only allow ``localhost``, ``.localhost``, ``127.0.0.1``, or the specified
hostname when running the dev server, to make debugger requests. Additional
hosts can be added by using the debugger middleware directly. The debugger
UI makes requests using the full URL rather than only the path.
:ghsa:`2g68-c3qc-8985`
-   Make reloader more robust when ``""`` is in ``sys.path``. :pr:`2823`
-   Better TLS cert format with ``adhoc`` dev certs. :pr:`2891`
-   Inform Python < 3.12 how to handle ``itms-services`` URIs correctly, rather
than using an overly-broad workaround in Werkzeug that caused some redirect
URIs to be passed on without encoding. :issue:`2828`
-   Type annotation for ``Rule.endpoint`` and other uses …
```
=> Upgrade werkzeug

requirements/prod.txt
No security patches but some crashes fixed here and there, so want to keep this up to date.
gevent changelog
```
24.2.1 (2024-02-14)
===================
Bugfixes
--------
- Add support for Python patch releases 3.11.8 and 3.12.2, which changed
internal details of threading.
As a result of these changes, note that it is no longer possible to
change the ``__class__`` of a ``gevent.threading._DummyThread``
object on those versions.
See :issue:`2020`.
Other
-----
Other updates for compatibility with the standard library include:
- Errors raised from ``subprocess.Popen`` may not have a filename set.
- ``SSLSocket.recv_into`` and ``SSLSocket.read`` no longer require the
buffer to implement ``len`` and now work with buffers whose size is
not 1.
- gh-108310: Fix CVE-2023-40217: Check for & avoid …
```
=> Upgrade gevent and greenlet

.github/workflows/build-and-release.yaml, .github/workflows/build-arm64.yaml
We've recently adapted github actions into this project. That work was based on a very old branch from 2.5 years ago we had at the beginning when we were only starting to port to ARM64. This was an experiment. That branch coincided with the time I was porting sync-engine to different versions of Python and it was 3.8 and 3.9 at the time. That's why we have them in matrix now but now Python 3.9 workflow just builds Python 3.8 images so it's defunct, complicates yaml file and only wasting us time and $.
=> Remove Python 3.9 from the build matrix

inbox/sqlalchemy_ext/json_util.py, inbox/sqlalchemy_ext/util.py, migrations/versions/057_consolidate_account_sync_status_columns.py, requirements/prod.txt
The original authors of this project chose to use pymongo's bson utils to handle JSON serialization and deserialization into various VARCHAR types in MySQL.
We have an unresolved security issue related to pymongo.
I've had questions in the past why are we using pymongo here, it suggests that sync-engine uses MongoDB while it does not. I think it's time to break that dependency because it just brings confusion, and pymongo will continue to receive security patches often as it contains C code which makes it prone to security bugs.
MongoDB's extended JSON syntax can serialize more types than stdlib's json module. [The docs](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/).
Pymongo's implementation sits in here https://github.com/mongodb/mongo-python-driver/blob/18328a9095 …
=> Remove pymongo dependency from this project

inbox/api/ns_api.py, inbox/util/debug.py, requirements/prod.txt
pyinstrument is a stack profiler for Python. I've never needed to use it in almost 3 years since most problems with sync-engine are connection/imap related and we don't really permanently install profilers into images anywhere else at Close. Would love to get rid off this as it has a c extension which slows down ARM builds.
=> Remove pyinstrument

.github/workflows/build-and-release.yaml, .github/workflows/build-arm64.yaml
This is another cleanup after we switched from CircleCI to GHA.
The downstream private repository expects the images to look like this:
for x86_64: `closeio/sync-engine:<sha>`
for arm64: `closeio/sync-engine:<sha>-arm64`
Because we had been using different format at the time we originally wrote GHA we didn't build ARM64 final images for like 2 months and I also had to fiddle manually with Dockerfiles there instead of using normal tooling we had, but that was not affecting production as we don't run ARM there. As I will be doing more work on sync-engine soon it's important to me that I can test things end to end locally on ARM.
We also don't build multiarch images anywhere else at Close, we experimented with this early when porting but then decided not to do it. I just deleted those steps …
=> Cleanup GHA workflows

inbox/util/rdb.py, requirements/prod.txt
This is very similar to https://github.com/closeio/sync-engine/pull/793.
Guppy is memory profiler and I have not used it in 3 years. I would probably use [memray ](https://github.com/bloomberg/memray) anyway these days which is far better. We don't ship profilers in the image to production anywhere elsewhere. It has C extensions that needs to be built from source on ARM and slows CI/CD down.
=> Remove guppy

requirements/prod.txt
Resolves CVEs. Bundled both of those libraries in one PR because both are backward compatible - no breaking changes and I never had problems with them before.
[Changelog
](https://raw.githubusercontent.com/kjd/idna/master/HISTORY.rst)
```
History
-------
3.7 (2024-04-11)
++++++++++++++++
- Fix issue where specially crafted inputs to encode() could
take exceptionally long amount of time to process. [CVE-2024-3651]
Thanks to Guido Vranken for reporting the issue.
3.6 (2023-11-25)
++++++++++++++++
- Fix regression to include tests in source distribution.
3.5 (2023-11-24)
++++++++++++++++
- Update to Unicode 15.1.0
- String codec name is now "idna2008" as overriding the system codec
"idna" was not working.
- Fix typing error for codec encoding
- "setup.cfg" has been added for this release due …
```
=> Upgrade dnspython and idna

inbox/models/message.py
The variable renamed here was shadowing the variable `message` from the outer scope.
=> Fix variable shadowing

inbox/contacts/remote_sync.py, inbox/events/remote_sync.py, inbox/mailsync/backends/base.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py, inbox/mailsync/gc.py, inbox/sync/base_sync.py
Component: sync pods
One of the things that I will need to do to port this to threading is switch all the places where sync-engine subclasses `gevent.Greenlet` to a similar `threading.Thread` class. Using `super()` This makes it easier because the subclass is not repeated in two places.
=> Sync pods: New style super

inbox/crispin.py, inbox/events/google.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/gc.py, inbox/sync/base_sync.py, inbox/util/concurrency.py, tests/events/test_google_events.py, tests/general/test_concurrency.py, tests/util/base.py
Component: sync pods
Sync-engine calls `gevent.monkey.patch_all()` before importing other modules.
`gevent.sleep()` is the same as patched `time.sleep()`, by using stdlib API we get closer to removing since `time.sleep()` works with `threading.Thread` as well.
=> Sync pods: replace gevent.sleep with time.sleep

inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py, inbox/mailsync/service.py
`greenlet.kill()` and `gevent.kill(greenlet)` do exactly the same thing.
By using OOO version we get get rid of `gevent` APIs. Python threads don't support `thread.kill()` but later when we switch to threads I'll implement a polyfill for this that emulates greenlet behavior as close as possible.
=> Sync pods: Use greenlet.kill() instead of gevent.kill(greenlet)

inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py, inbox/mailsync/service.py
I discovered in production that after merging reverted PR the shutdown time of sync containers has become much slower (20s versus almost 5 minutes).
So there's for sure a difference in practice between the two methods of killing the greenlets or some other factor that I do not know about yet that plays important role here.
I will investigate separately, for now let's revert it.
=> Revert "Sync pods: Use greenlet.kill() instead of gevent.kill(greenlet) (#827)"

inbox/crispin.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/service.py, tests/imap/test_folder_sync.py
Sync-engine calls gevent.monkey.patch_all() before importing other modules.
gevent APIs are the same as patched stdlib APIs, by using stdlib API we get closer to removing gevent and stdlib works with threading.Thread as well.
=> Sync pods: Replace gevent.lock.(Bounded)?Semaphore with threading.(Bounded)?Semaphore

inbox/mailsync/backends/base.py, inbox/mailsync/backends/imap/monitor.py
`gevent.pool.Group` has no equivalent in stdlib, but sync-engine uses such a small part of its API that we can easily substitute it with a list.
Conceptually a `gevent.pool.Group` is a container that keeps track of greenlets started in it. It also automatically removes `ready()` (greenlets that exited either successfully or because there was an exception) from the group.
The code in question is the account email sync parent greenlet that in a loop:
- asks IMAP what folders (Inbox, Sent, Trash, ...) are available 
- starts folder sync greenlets for the ones that are not already started, this is done with a group
Instead we can:
- start folders sync greenlet by calling their `.start()` explicitely and adding them to a list  (calling `gevent.pool.Group` starts a greenlet and adds it to the …
=> Sync pods: Replace gevent.pool.Group with a list

inbox/sync/base_sync.py
Sync-engine calls gevent.monkey.patch_all() before importing other modules.
[`gevent.event.Event`](https://www.gevent.org/api/gevent.event.html) APIs are the same as with `threading.Event` and we can use the latter with threads.
```python
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
True
>>> import threading
>>> threading.Event
<class 'gevent._gevent_cevent.Event'>
```
=> Sync pods: Replace gevent.event.Event with threading.Event

inbox/mailsync/backends/base.py
This should have been part of https://github.com/closeio/sync-engine/pull/841, but I was not careful enough when splitting the patch 🤡
=> Sync pods: Replace gevent.event.Event with threading.Event 2

Dockerfile
Sync-engine used to depend on pymongo, but I [removed that dependency](https://github.com/closeio/sync-engine/pull/771).
Previously I needed distutils and pinning setuptools version so I could build pymongo wheel, but since pymongo is no longer here we don't need those.
=> Remove packages that were needed to build pymongo

Dockerfile, requirements/prod.txt
I was revising the Docker image to realize that we have quite a number of packages that are not needed. Most of them used to be build time dependencies of Python packages that can be now installed from binary wheels.
This:
- Removes dependencies we don't use, so there's less of security updates needed
- Makes the images smaller ( 1.12GB -> 896MB )
- Makes the builds faster
=> Slim down docker images

Dockerfile
*I am not gonna deploy this on Friday, gonna wait til next week*
Ubuntu 20.04 LTS shipped with both 3.8 and 3.9, 3.8 is the default. We can switch to 3.9 and since this package is part of official Ubuntu repositories it will receive security updates in a way that is recognized by our security monitoring solution. My objective is going to 3.10, or maybe 3.11 (stretch) but since MySQL driver dropped support for gevent and the last version that supports gevent no longer works on 3.10 we are going through 3.9 first.
Going through 3.9 gives a one year safety runway if removing gevent proves to be more difficult than I think based on my PoCs.
I already did end 2 end manual testing and everything seems to be working, nonetheless I will be monitoring CPU, memory and ongoing syncs and be ready to …
=> Python 3.9

Dockerfile
This was prompted by an security alert from our security solution. It's claiming that linux package needs an update:
but querying dpkg shows that no `linux` package is present:
```
sync-engine@c1d3b7d8cc12:/opt/app$ dpkg -l | grep linux
ii  binutils-aarch64-linux-gnu 2.34-6ubuntu1.9                   arm64        GNU binary utilities, for aarch64-linux-gnu target
ii  libselinux1:arm64          3.0-1build2                       arm64        SELinux runtime shared libraries
ii  linux-libc-dev:arm64       5.4.0-193.213                     arm64        Linux Kernel Headers for development
ii  util-linux                 2.34-0.1ubuntu9.6                 arm64        miscellaneous system utilities
```
Nonetheless you can see that `linux-libc-dev` is present with the version matching the alert. …
=> Multistage Docker

inbox/mailsync/backends/imap/common.py, inbox/models/backends/imap.py, migrations/versions/261_add_ix_imapuid_account_id_folder_id_msg_uid_desc.py
This optimizes our hot running queries by using a better covering index, as I presented in front of the company.
The queries in question are:
```
SELECT imapuid.msg_uid AS imapuid_msg_uid FROM imapuid WHERE imapuid.account_id = 66368 AND imapuid.folder_id = 402004
SELECT MAX (imapuid.msg_uid) AS max_1 FROM imapuid WHERE imapuid.account_id = 66368 AND imapuid.folder_id = 402004
SELECT imapuid.msg_uid AS imapuid_msg_uid FROM imapuid WHERE imapuid.account_id = 66368 AND imapuid.folder_id = 402004 ORDER BY imapuid.msg_uid DESC LIMIT 100
```
Talking from experience it's not uncommon for those queries to return millions of message for a single folder. It's not uncommon to never delete your mail in 2024. That's why it's so important to have a dedicated index here.
The new index is faster because …
=> Better covering index for hot queries

inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/common.py, inbox/mailsync/backends/imap/generic.py
This rewrites one query which is off the beaten path and not that important from the performance point of view, I am doing this rather for consistency because this query *could* be faster. It also makes all those queries easier to find in the source code. This part of code is only executed if there's a new message in your folder which is "rare" compared to everything else that happens.
Also the code before actually fetches the row (to know the id) and we are only interested to know if it exists. That's what EXISTS clause in SQL exists for. This way we can read everything from the index and not look at the table at all because all the columns involved are already in the index.
Before
```sql
SELECT * FROM imapuid WHERE imapuid.account_id = %s AND imapuid.folder_id = %s AND imapuid.msg_uid = …
```
=> Some more FORCE INDEX

requirements/prod.txt
Resolves this alert, but also upgrading to the last version 1.26.20.
[Changelog](https://raw.githubusercontent.com/urllib3/urllib3/main/CHANGES.rst):
```
1.26.20 (2024-08-29)
====================
* Fixed a crash where certain standard library hash functions were absent in
FIPS-compliant environments.
(`#3432 <https://github.com/urllib3/urllib3/issues/3432>`__)
* Replaced deprecated dash-separated setuptools entries in ``setup.cfg``.
(`#3461 <https://github.com/urllib3/urllib3/pull/3461>`__)
* Took into account macOS setting ``ECONNRESET`` instead of ``EPROTOTYPE`` in
its newer versions.
(`#3416 <https://github.com/urllib3/urllib3/pull/3416>`__)
* Backported changes to our tests and CI configuration from v2.x to support
testing with CPython 3.12 and 3.13.
(`#3436 …
```
=> Upgrade urllib

.gitattributes, inbox/api/ns_api.py, inbox/models/message.py, inbox/util/blockstore.py, requirements/prod.txt, tests/util/test_blockstore.py, tests/util/tiny.eml
As presented during backend-sync zstandard can compress emails very well.
- For binary attachments like png/jpegs... it can reduce their size by 30% due to the fact that they are base64 encoded in MIME
- For longer English texts the compression can get as good as 5 times due the repetition of HTML and text parts that contain the same words
This lands the code and tests that use zstandard before saving the raw MIME data to blockstores.
In this PR I am not turning the compression on yet. This is controlled by config variable so this changes nothing so far.
There will be a separate PR to turn on `COMPRESS_RAW_MIME` in the downstream repository.
There will be also a separate PR with a script to recompress all the existing raw mimes.
=> Compress RAW MIMEs with zstandard

inbox/config.py, inbox/ignition.py
I will be porting off from Gevent one process at a time. I need a selective way to disable MySQL driver Gevent integration per pod because of that since all of the pods share the same db logic. This will be controlled by a environment variable for now.
=> Provide a way to disable gevent for mysql driver

bin/delete-marked-accounts.py, inbox/config.py, inbox/ignition.py
This is the simplest of our processes that can be trivially ported to threads.
- Remove gevent monkey patching
- Use a threadpool instead of list of greenlets
- Don't use gevent APIs, only sleep here. joinall is not needed because the context manager waits for all the threads to end.
* PR #895:
`drop-gevent-delete-account` ➔ `use-gevent`
* PR #894:
`use-gevent` ➔ `master`
=> Drop gevent in delete account pods

requirements/prod.txt
Bumping to the latest versions since I had no problems with both in the past, no breaking changes, only bugfixes and new features
webob
------
[Changelog](https://docs.pylonsproject.org/projects/webob/en/stable/changes.html)
```
1.8.7 (2021-02-17)
Bugfix
Decoding deflate-encoded responses now supports data which is packed in a zlib container as it is supposed to be. The old, non-standard behaviour is still supported.
See https://github.com/Pylons/webob/pull/426
```
zipp
----
[Changelog](https://zipp.readthedocs.io/en/latest/history.html)
```
v3.20.2
13 Sep 2024
Bugfixes
Make zipp.compat.overlay.zipfile hashable. ([#126](https://github.com/jaraco/zipp/issues/126))
v3.20.1
26 Aug 2024
Bugfixes
Replaced SanitizedNames with a more surgical fix for infinite loops, restoring support for names …
```
=> Bump webob & zipp

inbox/models/block.py
I've missed one place where we need to read RAW mime, we need to decompress it after reading from the blockstore (S3).
This happens when trying to import ical files for events (which we don't use in CRM since we read them directly from the calendar APIs). Nonetheless this triggers a Rollbar and should be fixed.
=> Bugfix: one more get_raw_mime instead of get_from_blockstore

inbox/mailsync/backends/imap/generic.py
Sync-engine can import events from ICS email message attachments. We don't use this, actually simply ignore them in CRM, since we rely on Google / Microsoft APIs tht are much better to sync those. Until now this only slows down the whole syncing process, uses extra db storage and also generates fair amount of Rollbars since we don't really maintain this code.
I will turn this config option off in the upstream repository.
=> Control if attached events are imported by config

inbox/api/wsgi.py, requirements/prod.txt
Adapted from https://til.codeinthehole.com/posts/how-to-get-gunicorn-to-log-as-json/.
Previously the way logging was done was hacky, i.e. we were subclassing internals of the gevent worker to make it work. This is not portable between different worker implementations (i.e. thread and gevent) and the implementation is just ugly. Gunicorn has a standard logging syntax described here https://docs.gunicorn.org/en/stable/settings.html#access-log-format that works between all of them. Also note that Gunicorn is not really designed to use structlog, it's just easier to bite the bullet and format stdlib logging with one of the JSON formatters like `json_log_formatter`.
I already deployed this to single workers to confirm that everything keeps working as expected.
The actual logdict configuration …
=> Gunicorn JSON logs, the universal way

requirements/prod.txt
We are not affected by any of the backward incompatible changes
Cryptography
--------------
[Changelog](https://cryptography.io/en/latest/changelog/)
```
43.0.1 - 2024-09-03[](https://cryptography.io/en/latest/changelog/#v43-0-1)
Updated Windows, macOS, and Linux wheels to be compiled with OpenSSL 3.3.2.
43.0.0 - 2024-07-20[](https://cryptography.io/en/latest/changelog/#v43-0-0)
BACKWARDS INCOMPATIBLE: Support for OpenSSL less than 1.1.1e has been removed. Users on older version of OpenSSL will need to upgrade.
BACKWARDS INCOMPATIBLE: Dropped support for LibreSSL < 3.8.
Updated Windows, macOS, and Linux wheels to be compiled with OpenSSL 3.3.1.
Updated the minimum supported Rust version (MSRV) to 1.65.0, from 1.63.0.
[generate_private_key()](https://cryptography.io/en/latest/hazmat/primi …
```
=> Upgrade certifi & cryprography

bin/inbox-start.py, bin/syncback-service.py
Greenlet tracers are used in sync & syncback processes (on by default), by they are not compatible with threading. They are responsible for detecting greenlets that did not switch to the event loop for too long and can optionally kill them. Those problems are greenlet specific but nonetheless happen from time to time especially in sync processes when parsing larger emails. With threads, even if something gets CPU bound, the Python VM will switch between threads after 5 milliseconds (or whatever you set in `setswitchinterval`), so those are not relevant anymore.
I want to keep the code for now if we need to rollback sync and/or syncback to greenlets because of any problems. At the end of porting I will remove `USE_GEVENT` flag and all the code that effectively becomes dead code.
=> Override enable_tracer without gevent

inbox/transactions/actions.py
Remove some gevent APIs that we can easily remove in the syncback process:
`gevent.event.Event` -> `threading.Event`
`gevent.lock.BoundSemaphore` -> `threading.BoundSemaphore`
`gevent.queue.Queue` -> `queue.Queue`
`gevent.pool.Group` -> `list`
Things still collaborate with gevent event loop due to monkey patching.
=> Syncback: remove some gevent APIs

bin/inbox-start.py, bin/syncback-service.py
This is a bugfix to https://github.com/closeio/sync-engine/pull/904.
When testing the previous version end to end I checked out the wrong branch and did not realize.
In both scripts the `config` is imported as `inbox_config` because `config` is a local variable for the main entrypoint :-/
Also if we had working mypy/type checking this kind of error would be caught early.
=> Bugfix: Override enable_tracer without gevent

tests/api/test_folders.py, tests/imap/test_actions.py, tests/scheduling/test_syncback_logic.py
I've identified some tests that start greenlets but forget to stop them afterwards. Those greenlets go away at the end of the test suite but this is just not clean, pollutes other test and makes debugging concurrency bugs harder.
=> Tests: Stop leaking running greenlets from test cases

bin/check-attachments.py, bin/inbox-api.py, bin/inbox-auth.py, bin/inbox-console.py, bin/remove-message-attachments.py, bin/restart-forgotten-accounts.py, bin/syncback-stats.py
This ports all the scripts that we are not running in k8s pods.
While porting and testing I found out that some of them were already broken before and I fixed them.
Note that we have to pass `config["USE_GEVENT"] = False` since some of the code is still shared with sync and syncback pods that were not fully ported away from gevent.
- Port bin/check-attachments.py
- Port bin/inbox-auth.py
- Port bin/inbox-api.py
- Port bin/inbox-console.py
- Port bin/remove-message-attachments.py
- Port bin/restart-forgotten-accounts.py
- Port bin/syncback-stats.py
=> Scripts: Remove gevent

bin/inbox-start.py, inbox/mailsync/service.py
Ports off this functionality from `gevent.spawn_after` API.
Note that we are using this functionality in production to automatically cycle pods from time to time and avoid memory leaks (yes they are there in the first place and we just deal with them like that since forever LOL)
So the process can end on signals, or exit automatically somewhere between `--exit-after=min_minutes:max_minutes`. The values we are using in production are `--exit-after=240:360` which is somewhere between 4 and 6 hours.
This is done in thread-land with a daemon thread that sleeps and calls sync_service stop(). I moved the whole logic away from the class because this is very similar to how signals are handled.
Why daemon? Because the interpreter does not wait for daemon threads to exit before shutting down, …
=> Sync: Port --exit-after to threads

inbox/mailsync/backends/base.py, inbox/mailsync/backends/imap/generic.py, inbox/mailsync/gc.py, inbox/sync/base_sync.py
I'm in the process of hunting memory leaks in sync-engine. memray can split leaks by threads and having the names in the flamegraph speeds up the work of pinning the down and fixing them. Other profilers typically use this info as well.
=> Add thread names

requirements/prod.txt
I am in the process of hunting memory leaks with [memray](https://github.com/bloomberg/memray). While analyzing the parts of the program that allocate memory faster than they deallocate I've seen a lot of stack traces inside sqlalchemy. E.g.
This lead me to suspect that the version of sqlalchemy sync-engine uses has memory leaks.
I started reading the changelog and quickly spotted that there are indeed changes that fix memory leaks/improve memory usage that we are missing i.e.:
https://docs.sqlalchemy.org/en/20/changelog/changelog_14.html#change-1.4.44
> Fixed critical memory issue identified in cache key generation, where for very large and complex ORM statements that make use of lots of ORM aliases with subqueries, cache key generation could produce excessively large keys that were …
=> Upgrade sqlalchemy

inbox/crispin.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/common.py, inbox/mailsync/backends/imap/generic.py
I'm currently hunting memory leaks in sync pods. While running [memray](https://github.com/bloomberg/memray) in production I noticed that we are holding a lot of references to collections of integers. This is not a surprise to me as a single folder can have tens of millions of messages these days. Nonetheless we were holding references for too long, and sometimes buffering/copying twice for no good reason. This PR fixes those problems.
=> Reduce memory pressure

bin/inbox-start.py, inbox/mailsync/backends/base.py, inbox/mailsync/service.py
This fixes some of the perils of concurrent programming...
First of all we were killing greenlets inside a signal handler which you should never do as those operations are not safe to run there ending up in `gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback`. I moved them outside the signal handler and now they run after the main loop of the program ends after signal handler is received. 
On this branch sync-engine exists without exceptions
```
{"greenlet_id": 281473418792448, "env": "prod", "event": "stopping sync process", "timestamp": "2024-10-02T12:10:27.258759Z", "level": "info", "module": "inbox.mailsync.service:379"}
{"provider": "imap", "account_id": 4, "greenlet_id": 281473279804256, "env": "prod", "event": "mail sync …
```
=> Sync: Fix stopping

inbox/crispin.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py, tests/imap/test_actions.py, tests/imap/test_crispin_client.py
As stated before a single folder can have millions of messages, and millions of IMAP uid integers. We were buffering to lists in intermediate functions while we can just generate one int at a time using generators and buffer to set when we really need to (because we need to calculate differences between what we have in the database and what's remotely on IMAP server to decide what to delete locally and what to create locally).
=> Use generators to save memory

bin/inbox-start.py, inbox/mailsync/backends/base.py, inbox/mailsync/service.py, inbox/transactions/actions.py, inbox/util/concurrency.py
This is a bugfix for https://github.com/closeio/sync-engine/pull/921.
When the original PR was deployed I noticed that the sync shutdown has become much slower in production i.e. minutes instead of seconds. This made the whole deploy process much slower. This is because I was now correctly waiting for all the greenlets but I was killing them one by one mostly and waiting for them to finish one by one at the same time. I know tweaked this to kill them one by one without waiting and then waiting for all of them to finish.
There's also a bug that crept in again because of too many branches/too much rebasing.
=> Kill greenlets faster

inbox/mailsync/backends/imap/generic.py
This reduces memory pressure because otherwise the reference is held until the end of the function. In particular this variable can hold millions of ints for a single email folder and it's not uncommon these days. It's not used later in this function.
=> One more del

inbox/mailsync/backends/gmail.py, inbox/mailsync/gc.py, inbox/mailsync/service.py, tests/imap/test_save_folder_names.py
Sometimes I can't believe how sloppy this codebase is, and it works very well nonetheless.
There were more run-away greenlets - e.g. greenlets that were spawned but were not correctly killed. This is bad since this can slow down the process shutdown. Also we were leaking them in tests in one place which could lead to polluting another test results.
I spotted this since these kinds of problems are actually worse with run-away threads.
=> More runaway greenlets

inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/service.py, inbox/util/concurrency.py
To stop even faster (I care about this because it affects how fast deploys go out) we can stop all the email syncs in parallel since they are totally independent and order does not matter.
=> Stop mail syncs in parallel

inbox/mailsync/backends/gmail.py
Testing email syncing, I encountered an error.
When the `if self.is_all_mail(crispin_client):` path isn't taken (because email can't sync?) then there is no `inbox_uids` defined.
```
File "/opt/app/inbox/util/concurrency.py", line 75, in wrapped
return func(*args, **kwargs)
File "/opt/app/inbox/mailsync/backends/imap/generic.py", line 291, in _run_impl
self.state = self.state_handlers[old_state]()
File "/opt/app/inbox/util/concurrency.py", line 75, in wrapped
return func(*args, **kwargs)
File "/opt/app/inbox/mailsync/backends/imap/generic.py", line 421, in initial_sync
self.initial_sync_impl(crispin_client)
File "/opt/app/inbox/mailsync/backends/gmail.py", line 300, in initial_sync_impl
del inbox_uids  # free up memory as soon as possible …
```
=> Only free inbox_uids if defined

inbox/interruptible_threading.py, tests/test_interruptible_threading.py
This is a secret sauce that will let me convert syncback and sync pods to threading without doing a complete rewrite. Both sync and syncback processes are trees of greenlets and they need to become trees of threads.
Greenlets can be killed in any place you are calling gevent-native API or monkey patched stdlib. Internally this raises exceptions both in greenlets and on this branch but normally you don't see this because it happens behind the scenes. I provided a polyfill that lets me replace the Greenlet base classes with InterruptibleThread. This polyfill provides greenlet-like methods/properties and emulates greenlets as close as practically possible. The threads must call `check_interrupted` from time to time or use conveniently provided `interruptible_threading.sleep` and others …
=> Interruptible threading

bin/inbox-start.py, bin/supervisor.py
We have a supervisor script written in Python in the downstream repository. I moved it to this repository because it's written in Python and it was also not handling nicely all the edge cases and I needed to improve it.
* The other supervisor will just hang if the supervised child process never handles SIGTERM or gets stuck in the shutdown.
* Previously the `--exit-after` was handled in the child, in our case `sync` process. As sync process is pretty complex and runs a lot of things it's safer to have this critical functionality in the supervisor process.
=> Move and improve supervisor to this repository

bin/syncback-service.py, inbox/transactions/actions.py, inbox/util/concurrency.py, tests/conftest.py, tests/general/test_concurrency.py, tests/util/base.py
Stacked on: https://github.com/closeio/sync-engine/pull/944
Remove gevent from syncback using interruptible threads. As you can see the diff is minimal. I already tested this end to end.
This also removes gevent from the test suite because we are at the point it can be done.
=> Synback: Remove gevent

bin/inbox-start.py, inbox/crispin.py, inbox/events/google.py, inbox/events/microsoft/events_provider.py, inbox/interruptible_threading.py, inbox/mailsync/backends/base.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/frontend.py, inbox/mailsync/gc.py, inbox/sync/base_sync.py, inbox/util/concurrency.py
Sync: Remove gevent
Stacked on https://github.com/closeio/sync-engine/pull/911
This again takes advantage of `IterruptibleThread` polyfill. The changes are
* changing base classes from `Greenlet` to `InterruptibleThread`.
* Added `check_interrupted` calls around I/O and other places it makes sense
* blocking calls like sleep become iterruptible etc.
=> Sync: Drop gevent

inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/generic.py
We are running on threads in production now. I observed CPU & RAM usage balloon on some of the pods where we run a lot of accounts. This is because with gevent CPU & RAM intensive sections are "naturally" locked - i.e. gevent will only switch between greenlets when you use gevent APIs or I/O - threads on the other hand can switch every N-th Python bytecode. This in turn makes it possible to allocate faster and have bigger spikes in CPU usage. I tried this branch already in production and it solves the problem without slowing down or negatively impacting syncs. It just brings back the "natural" gevent behavior.
This adds `with self.global_lock` sections around CPU & RAM intensive operations so threads don't switch between each other in those sections and don't inflate CPU & RAM usage. The …
=> Lock some CPU & RAM intesitve operations

inbox/models/message.py
Related to https://github.com/closeio/sync-engine/pull/948
> We are running on threads in production now. I observed CPU & RAM usage balloon on some of the pods where we run a lot of accounts. This is because with gevent CPU & RAM intensive sections are "naturally" locked - i.e. gevent will only switch between greenlets when you use gevent APIs or I/O - threads on the other hand can switch every N-th Python bytecode. This in turn makes it possible to allocate faster and have bigger spikes in CPU usage. I tried this branch already in production and it solves the problem without slowing down or negatively impacting syncs. It just brings back the "natural" gevent behavior.
Another CPU/RAM intensive part is email parsing. I've locked this and tried in production and CPU usage alarms went away …
=> Lock email parsing

inbox/mailsync/backends/imap/generic.py, inbox/sync/base_sync.py, inbox/util/concurrency.py
This address two problems I realized after starring for too much time at our metrics:
First, sync engine sync pods are essentially doing concurrently:
- wait for something or sleep some period of time
- fetch remote state (IMAP or Calendar), fetch local state (MySQL) - compare - update local state to reflect remote state
There are around 400 concurrent of those checks happening per sync pod (every single IMAP folder in every single account, every calendar etc.). They all use the same poll intervals meaning that they wake all up at the same time more or less and create momentary CPU and RAM spikes in metrics. It's better to jitter that a little bit to smooth-en metrics and load out.
Second, for servers that support it (Gmail does for example) we use IMAP IDLE - this basically tells the …
=> Introduce jitter

inbox/mailsync/backends/imap/common.py, inbox/sqlalchemy_ext/util.py
This function is called a lot and it shows in the profiles as the busiest function. I've used [py-spy](https://github.com/benfred/py-spy) to obtain those profiles in production.
I discovered that the SQLAlchemy "post-processing" which just creates intermediate objects to handle all the possible shapes that SQLAlchemy supports takes significant portion of this function runtime. You can see a lot of SQLAlchemy fiddling below the call to it, the actual execution in MySQL is 50% of time.
Since this is a trivial query that returns a single column we can easily rewrite it to use driver's DB-API which is still portable between different databases ([PEP](https://peps.python.org/pep-0249/)) which means that it's 2 times faster now as it only spends time executing.
Just the other day I was dealing …
=> Skip SQLAlchemy when fetching millions of UIDs

Dockerfile, inbox/util/concurrency.py, requirements/prod.txt, tests/general/test_concurrency.py
So we are running very outdated version of mysql database driver (from 2019)... because they removed support for gevent long time ago. This also prevented us from updating to newer  Python versions (Past 3.9) because that old version of the driver no longer compiles on newer Pythons. Now that gevent is gone it's time to rectify this... Thank heavens there was not a single CVE against this in all those years, otherwise we would be screwed.
I tried this end to end locally but will also do canaries.
[Changelog](https://github.com/PyMySQL/mysqlclient/blob/main/HISTORY.rst):
```
What's new in 2.2.5
Release: 2024-10-20
(Windows wheel) Update MariaDB Connector/C to 3.4.1. #726
(Windows wheel) Build wheels for Python 3.13. #726
What's new in 2.2.4
Release: 2024-02-09
Support ssl=True in …
```
=> Bump mysqlclient version

requirements/prod.txt
Needed for later versions of Python.
[Changelog](https://cffi.readthedocs.io/en/latest/whatsnew.html)
```
v1.17.1[¶](https://cffi.readthedocs.io/en/latest/whatsnew.html#v1-17-1)
Fix failing distutils.msvc9compiler imports under Windows ([#118](https://github.com/python-cffi/cffi/pull/118)).
ffibuilder.emit_python_code() and ffibuiler.emit_c_code() accept file-like objects ([#115](https://github.com/python-cffi/cffi/pull/115)).
ffiplatform calls are bypassed by ffibuilder.emit_python_code() and ffibuilder.emit_c_code() ([#81](https://github.com/python-cffi/cffi/pull/81)).
v1.17.0
In API mode, when you get a function from a C library by writing fn = lib.myfunc, you get an object of a special type for performance reasons, instead of a <cdata ‘C-function-type’>. Before version 1.17 you could …
```
=> Update cffi version

Dockerfile, inbox/util/html.py
Supersedes: https://github.com/closeio/sync-engine/pull/439
=> Python 3.10

inbox/util/logging_helper.py
After replacing boto with boto3 in [this PR](https://github.com/closeio/sync-engine/pull/961) I've seen in production that it started logging a lot.
```
2024-10-29 15:02:30.400	s3transfer.utils - DEBUG: Releasing acquire 0/None
2024-10-29 15:02:30.398	s3transfer.tasks - DEBUG: Executing task PutObjectTask(transfer_id=0, {'bucket': '...', 'key': '...', 'extra_args': {}}) with kwargs {'client': <botocore.client.S3 object at 0x73310037efe0>, 'fileobj': <s3transfer.utils.ReadFileChunk object at 0x733130fc3850>, 'bucket': '...', 'key': '...', 'extra_args': {}}
```
Every time it uploads something to S3, and it does it a lot taking a lot of logging space. Previously we had boto tweaked here already so we just need to tweak s3transfer similarly.
=> Tune logging for s3transfer

Dockerfile, requirements/prod.txt
I've already started testing this end to end on single pods where my email is synced, will of course do a canary.
TODO:
* PR #960:
`python-312` ➔ `python-310`
* PR #959:
`python-310` ➔ `master`
=> Python 3.12

bin/sync-single-account.py, inbox/mailsync/backends/base.py, inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/service.py
This is something that I did over and over using sync-engine console to debug escalations and otherwise troubleshoot syncing of a single account. Since it is not obvious how to do it I wrapped it in a script so everybody can use it.
=> sync-single-account.py

inbox/mailsync/backends/imap/common.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/gc.py, tests/imap/test_delete_handling.py
We have some non-conforming generic IMAP servers that sometimes can show the same message under thousands of IMAP uids.
Normally a message can show at most two, maybe three times if it's moved between different folders quickly as there's inevitably a delay before we detect it disappeared and sometimes it will be after we already detected addition to another folder. There's also not a standard way of detecting moves in IMAP so it looks like additions and deletions to sync-engine so this is just how things are.
But sometimes there are those generic IMAP servers that report the same message appearing thousands of times in the same folder, which is nonsense, and sync-engine was not ready for that as it tried to load all the ImapUids objects using ORM which exploded CPU and RAM usage. I've …
=> Limit ORM usage for ImapUids objects

inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/common.py, inbox/models/backends/imap.py, tests/imap/test_delete_handling.py, tests/imap/test_labels.py, tests/imap/test_update_metadata.py
After https://github.com/closeio/sync-engine/pull/969 we got RAM and CPU usage under control.
The other problem with this code is that it can be painfully slow, especially with large deletions.
I know we have at least on escalation because of the slowness of this code where customer is using automation to move large amounts of emails between folders.
There are two problems here:
- For non conforming IMAP servers that can list one message under many uids we were deleting uids one by one and then updating a message, for such cases it's thousand of times much faster to delete all the uids in one go and then update message.
- We had N+1 queries when recalculating email categories
=> Batch and optimize large deletions

inbox/mailsync/backends/gmail.py, inbox/mailsync/backends/imap/common.py, inbox/models/backends/imap.py, tests/imap/test_delete_handling.py, tests/imap/test_labels.py, tests/imap/test_update_metadata.py
This touches email categorization code, and that is when an email is categorized as inbox or not. We've been seeing some emails not categorized as inbox. Want to revert this to confirm that it's this indeed.
=> Revert "Batch and optimize large deletions (#971)"

inbox/mailsync/backends/imap/common.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/gc.py, tests/imap/test_delete_handling.py
This reverts commit c66d90911a64cf4130d821a730f9980243736b71.
This touches the same email categorization code as 
https://github.com/closeio/sync-engine/pull/975, so let's revert it for now.
=> Revert "Limit ORM usage for ImapUids objects (#969)"

requirements/prod.txt
Addresses [CVE-2024-49767](https://nvd.nist.gov/vuln/detail/CVE-2024-49767)
Dependencies before upgrade (from `pipdeptree -p werkzeug`):
```
Werkzeug==3.0.3
└── MarkupSafe [required: >=2.1.1, installed: 2.1.2]
```
Dependencies after upgrade (from `pipdeptree -p werkzeug`):
```
Werkzeug==3.0.6
└── MarkupSafe [required: >=2.1.1, installed: 2.1.2]
```
Changelog:
```
Version 3.0.6
-------------
Released 2024-10-25
-   Fix how ``max_form_memory_size`` is applied when parsing large non-file
fields. :ghsa:`q34m-jh98-gwm2`
-   ``safe_join`` catches certain paths on Windows that were not caught by
``ntpath.isabs`` on Python < 3.11. :ghsa:`f9vj-2wh5-fj8j`
Version 3.0.5
-------------
Released 2024-10-24
-   The Watchdog reloader ignores file closed no write events. :issue:`2945`
-   Logging works …
```
=> Upgrade Werkzeug to 3.0.6

inbox/providers.py
Add support for the alternate folder name "INBOX.Archiv" to properly map it to the "archive" folder. This enhances compatibility with email providers using this naming convention.
We previously [added support for German "archiv"](https://github.com/closeio/sync-engine/pull/468) to the default folders. Custom providers use the `INBOX.Archive` format, and we now have a German custom email provider that uses `INBOX.Archiv`.
=> Map "INBOX.Archiv" to "archive" in folder settings

.github/workflows/build-and-release.yaml, Dockerfile
Normally, steps in a Docker build are cached to save time.
This change will let us trigger an almost full rebuild of the Docker image via an empty commit containing `#nobuildcache` in the message.
Such a rebuild may be necessary if we want to get upgraded versions of packages that we'd otherwise get from the cache.
Also, this PR fixes the `DOCKER_WEEK` Dockerfile argument that's supposed to bust the cache every week.
=> Allow busting cache in docker builds and fix `DOCKER_WEEK`

.github/workflows/build-and-release.yaml
Apparently using `*` breaks for branches with `/` in the name.
=> Fix the GitHub Actions workflow for branches with `/` in the name

inbox/logging.py, requirements/requirements-prod.in, requirements/requirements-prod.txt
Changelog: https://github.com/hynek/structlog/blob/main/CHANGELOG.md
The upgrade is needed to get this fix for `render_to_log_kwargs`: https://github.com/hynek/structlog/pull/427
I need it for the Sentry integration.
Not seeing anything too risky in the changelog.
That said, I wouldn't ship this before the end of the company holidays.
=> Upgrade `structlog` from `21.4.0` to `23.1.0`

inbox/models/block.py
Fixes an issue where long attachment content types can cause database errors.
We've been getting the following error, because for one of the emails, an attachment's `Content-Type` header contained the base64-encoded attachment body for some reason (probably a bug on the side of one of the email providers):
```
DataError: (MySQLdb.DataError) (1406, "Data too long for column '_content_type_other' at row 1")
[SQL: INSERT INTO block (public_id, updated_at, deleted_at, data_sha256, size, _content_type_common, _content_type_other, filename, namespace_id) VALUES (...)
```
=> Truncate long `Block.content_type`

inbox/mailsync/backends/gmail.py
Fixes the logging module erroring with ValueError("Attempt to overwrite 'name' in LogRecord")
=> Rename `name` extra to `log.info`.

inbox/api/srv.py
Fixes the following error:
```
File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 1396, in handle_exception
handler = self._find_error_handler(server_error)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 1242, in _find_error_handler
handler = handler_map.get(cls)
^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'get'
```
It is prudent to not return exception information in API responses anyway.
=> Remove a broken Flask error handler

inbox/error_handling.py
Sync-engine is currently capable generating a huge volume of errors, so it's a good idea to limit what we send to Sentry for now.
=> Set Sentry sample rate to `0.1`

inbox/config.py, inbox/events/microsoft/events_provider.py, inbox/events/microsoft/graph_types.py, inbox/events/microsoft/parse.py, tests/events/microsoft/test_events_provider.py, tests/events/microsoft/test_parse.py
Migrating to `iCalUId` gives us immutable event IDs for calendar events synced from the MS Graph API. In the past, any event synced to multiple user's calendars would get unique event IDs from MS. This would make them look like distinct events to the consuming application, assigning users to the same meeting multiple times.
With `iCalUId`, we can avoid this issue and have behavior similar to gmail. To avoid creating duplicates with all events synced prior to this change, a cutoff date can be used.
=> Migrate MS Events to use `iCalUId` for events created after cutoff date

inbox/mailsync/backends/base.py, inbox/mailsync/backends/imap/monitor.py, inbox/mailsync/service.py
`BaseMailSyncMonitor` is a thread that does nothing other than create, start, and join another thread. It might as well just run the code synchronously itself.
=>  Do not create an extra thread to run sync
