closeio/sync-engine

inbox/util/threading.py

This helps with some edge cases where a common transactional email can return
thousands of threads and hundreds of thousands of messages. Scanning through
them all can block the greenlet and cross the threshold of 60s
(`MAX_BLOCKING_TIME_BEFORE_INTERRUPT`).

Bail out of `fetch_corresponding_thread` after scanning 20K messages.

---

inbox/util/threading.py

This iterates on the [previous commit ](https://github.com/closeio/sync-engine/commit/55298ee30beb6145e1e880e7b486452934e9084d) by optimizing & limiting the database
query to avoid memory issues.

Improve `fetch_corresponding_thread` optimization

---

inbox/auth/base.py
inbox/auth/generic.py
inbox/auth/google.py
inbox/auth/utils.py
inbox/models/backends/generic.py
inbox/sendmail/smtp/postel.py
inbox/util/testutils.py
migrations/versions/253_drop_require_ssl.py
tests/api/test_account.py
tests/imap/test_smtp.py

Requires https://github.com/closeio/sync-engine/pull/28 first (because the migrations are in sequence).
Deploy PR first, and only run migration when it's fully rolled out.

Always require an encrypted connection for IMAP & SMTP

---

docker-compose.yml

Updates MySQL to the latest 5.7 build at time of writing.

Update MySQL to 5.7.31

---

inbox/api/srv.py

Black formatting

---

.circleci/config.yml
.flake8

This is a stripped down version of https://github.com/closeio/sync-engine/pull/59 that I would later use to fix each group of errors on separate PRs.

Just enable Flake8

---

.circleci/artifacts.html
.circleci/config.yml
docker-compose.yml
requirements_frozen.txt

Rendered: https://469-278426826-gh.circle-artifacts.com/0/pythoncov/index.html

Enable coverage reports

---

tests/search/conftest.py

Does not seem to have any purpose

Remove superfluous tests.search module

---

.flake8
inbox/api/ns_api.py
inbox/s3/backends/gmail.py
tests/api/test_filtering.py

Flake8: Remove extra format args

---

requirements_frozen.txt

> Pyinstrument is a Python profiler. A profiler is a tool to help you optimize your code - make it faster.
This is only used in debug mode. This is the last version that works on Python 2.

Upgrade pyinstrument

---

requirements_frozen.txt

> Pympler is a development tool to measure, monitor and analyze the memory behavior of Python objects in a running Python application.
This is the last version, it still works on Python 2.
We use only two functions from this module and I confirmed manually that things keep working:
https://github.com/closeio/sync-engine/blob/28b5adb8896320dd8011bb5b270dcd9a14a822bc/inbox/mailsync/frontend.py#L72-L74

Upgrade pympler

---

requirements_frozen.txt

These packages are not used anywhere in the code.

Remove websocket & socketio

---

requirements_frozen.txt

Upgrade mockredispy

---

requirements_frozen.txt

Library not used in the codebase.

Remove python-magic

---

requirements_frozen.txt

Upgrade freezegun

---

requirements_frozen.txt

Upgrading all the way to the latest version. We use boto to contact S3 to read write mail blocks.
We have now tests that test it e2e so this is safe.
Changelog
```
2.49.0
============
:date: 2018/07/11
Updated the CA Bundle as well as some bucket encryption fixes.
Changes
-------
* Import the latest CA Bundle from certifi (:issue:`3818`, :sha:`e4699cba`)
* Fix to support uploads to KMS-encrypted buckets. (:issue:`3800`, :sha:`0a1d9040`)
* Support fetching GCS bucket encryption metadata. (:issue:`3799`, :sha:`132b64d2`)
* Update layer1.py (:issue:`3765`, :sha:`53340159`)
* Fix tests/unit/glacier/test_writer.py to make work with pypy. (:issue:`3762`, :sha:`8402c5d6`)
2.48.0
============
:date: 2017/06/29
This release addresses a few S3 related bugs as well as a bug with the recent
endpoint …
```

Upgrade boto

---

.circleci/config.yml

Reaching that sweet spot where tests pass on 3.6 and 3.8.

Tests must pass on 3.6 and 3.8

---

inbox/__init__.py
inbox/client/__init__.py
inbox/client/client.py
inbox/client/errors.py
inbox/client/restful_model_collection.py
inbox/client/restful_models.py
inbox/client/util.py
requirements_frozen.txt
tests/system/client.py

This is a vendroing in of nylas==1.2.3. I need this vendored to keep updating dependencies and modernizing the whole thing.
We vendored before nylas-production-python in https://github.com/closeio/sync-engine/pull/75

Vendor nylas

---

inbox/auth/base.py
inbox/crispin.py
inbox/mailsync/backends/imap/generic.py
inbox/models/util.py

More of: https://github.com/closeio/sync-engine/pull/216

More exception messages

---

inbox/models/account.py

More of https://github.com/closeio/sync-engine/pull/218

One more exception message compatibility fix

---

.circleci/config.yml
Dockerfile
requirements/lint.txt
requirements/prod.txt
requirements/test.txt

This splits requirements into separate files like we do in other projects. Note that test requirements are still always installed because we need them in the image in devtools.

Split requirements

---

requirements/test.txt

This is the latest version of pytest. It only works on Python 3.x so it has to be guarded.

Upgrade pytest & friends

---

migrations/versions/001_rename_message_id_to_message_id_header.py
migrations/versions/005_import_old_accounts.py
migrations/versions/017_haspublicid.py
migrations/versions/019_blocks_to_parts.py
migrations/versions/022_webhooks_and_filters.py
migrations/versions/023_tighten_nullable_constraints_on_.py
migrations/versions/024_remote_folders_and_inbox_tags_split.py
migrations/versions/028_tag_api_migration.py
migrations/versions/038_add_public_ids_to_transactions.py
migrations/versions/040_gmailaccount.py
migrations/versions/047_store_more_on_threads.py
migrations/versions/050_imap_table_cleanups.py
migrations/versions/056_message_unique_constraint.py
migrations/versions/064_make_address_fields_non_null.py
migrations/versions/084_mutable_drafts.py
migrations/versions/085_add_attachment_tag.py
migrations/versions/094_eas_passwords.py
migrations/versions/115_eas_twodevices_turn.py
migrations/versions/150_add_polymorphic_events.py
migrations/versions/155_add_status_column.py
migrations/versions/156_drop_cancelled_column.py
migrations/versions/160_split_actionlog.py
migrations/versions/161_update_eas_schema_part_3_for_prod.py
migrations/versions/174_backfill_owner2.py
migrations/versions/175_fix_recurring_override_cascade.py
migrations/versions/180_migrate_event_descriptions.py

Fix migrations for Python 3

---

requirements/prod.txt

Changelog
```
0.16.2
- Fix building person data in Django. See [385](https://github.com/rollbar/pyrollbar/pull/385)
- Fix circular error logging for non-HTTP events in Starlette. See [390](https://github.com/rollbar/pyrollbar/pull/390)
- Fix Python 3.4 builds. See [389](https://github.com/rollbar/pyrollbar/pull/389)
```

Upgrade rollbar

---

requirements/prod.txt

These are backports of Python 3 funcionality to Python 2.

Gate some packages

---

requirements/prod.txt

Remove some packages

---

requirements/prod.txt

Upgrade the certificate store.

Upgrade certifi

---

.circleci/config.yml

Provide ways to skip tests using #notests similary to other repositories.This is sometimes useful when reverting but should be used with care of course.

Skip tests

---

requirements/prod.txt

This is a backport. Python 2.7 only dep.

Gate singledispatch

---

requirements/prod.txt

Remove colorama

---

requirements/prod.txt

This is a backport. Python 2.7 only dep.

Gate scandir

---

requirements/prod.txt

Remove wrapt

---

.circleci/config.yml
Dockerfile

Note that we won't push images. This is just to ensure I don't break them accidentally.

Enable tests on Python 3.7 & 3.9

---

.flake8
bin/backfix-generic-imap-separators.py
bin/set-throttled.py
inbox/api/ns_api.py
inbox/crispin.py
inbox/security/oracles.py
inbox/util/rdb.py
inbox/util/testutils.py
requirements/lint.txt
tests/api/test_event_when.py
tests/api/test_events.py
tests/general/test_namespace.py
tests/imap/test_crispin_client.py
tests/system/conftest.py
tests/system/test_drafts.py
tests/system/test_labels.py
tests/system/test_sending.py

Many of those would benefit from fstrings but we can't until January when we plan to drop Python 2.7.
Settings from other project of ours. I left an issue for reviewing places where fstrings would simplify things: https://github.com/closeio/sync-engine/issues/296

Remove percent formatting aka flake8-sfs

---

inbox/models/backends/oauth.py
tests/test_misc.py

Log access/storage of access and refresh tokens

Log token usage

---

inbox/error_handling.py
tests/general/test_concurrency.py

See: https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L468
Example in the docs of extra_data usage: https://docs.rollbar.com/docs/python#examples

Extra data in Rollbar

---

Dockerfile

Reverts closeio/sync-engine#329
There's some sort of issue with this (likely minor/just related to the path), but I'll revert for now until I get a chance to properly look into it.

Revert "Refactor docker image to a multi-stage image for smaller final image size."

---

.git-blame-ignore-revs

Followed the structure we have in another repository of ours.

Introduce .git-blame-ignore-revs

---

.circleci/config.yml
Dockerfile

Making sure we regularly get OS updates

Add build week

---

requirements/prod.txt

Same as https://github.com/closeio/quotequail/pull/35/files

Lxml 4.9.1

---

inbox/sqlalchemy_ext/util.py

While looking around I realized this is no longer used by anything

Remove maybe_refine_query

---

inbox/mailsync/frontend.py

The HTTPFrontend base class is only inherited by ProfilingHTTPFrontend which means it should not be a separate entity. This also confuses mypy.

Merge HTTPFrontend with ProfilingHTTPFrontend

---

inbox/mailsync/backends/base.py

This is part of my ongoing crusade to make static typing analysis work in this project.
This class has an abstract `sync()` method and and it also starts a greenlet stored on `self.sync` which overwrites `sync()` method. The greenlet runs `sync()` method. Since the reference to `sync()` method is passed into `Greenlet` constructor before it's overwritten everything keeps working at runtime...
But this confuses IDE, mypy and probably real humans as well. Let's keep the greenlet and the body it executes separate because they are different things.

Stop overwriting sync() method with sync greenlet in BaseMailSyncMonitor

---

.circleci/config.yml
inbox/actions/backends/gmail.py
inbox/api/metrics_api.py
inbox/api/update.py
inbox/api/validation.py
inbox/api/wsgi.py
inbox/contacts/abc.py
inbox/contacts/algorithms.py
inbox/contacts/google.py
inbox/contacts/icloud.py
inbox/contacts/remote_sync.py
inbox/events/google.py
inbox/events/ical.py
requirements/lint.txt
setup.cfg

Step by step. This adds annotations module by module, as turning mypy on the whole codebase would be hard and a big PR.

Mypy: module by module

---

inbox/auth/oauth.py
requirements/prod.txt

https://github.com/closeio/authalligator-client/pull/14

Bump `authalligator-client`

---

inbox/crispin.py
inbox/mailsync/backends/imap/monitor.py

Found one more place, we do the same check.

Don't explode on missing inbox folder

---

inbox/events/ical.py

This eventually will be a warning but I want to collect timezone IDs we currently choke on, to see if we could recover.

ICS timezone parsing, better exception

---

inbox/events/microsoft_graph_client.py
requirements/test.txt
tests/events/test_microsoft_graph_client.py

Implement subset of Microsoft Graph API to read from Outlook Calendars.
Quick demo:
https://user-images.githubusercontent.com/754356/196475104-60094987-b041-4b2c-9fa5-aa1b10279aa7.mp4

Microsoft Graph Client

---

inbox/events/microsoft/graph_types.py
inbox/events/microsoft/parse.py
tests/events/microsoft/test_parse.py

This contains an algorithm to translate Microsoft Graph [PatternedRecurrence](https://learn.microsoft.com/en-us/graph/api/resources/patternedrecurrence) to iCal RRULE. We need this as the whole system operates on RRULEs.

Convert Microsoft Graph RecurrencePattern to iCal RRULE

---

inbox/auth/base.py

I'm suspecting this is only happening on generic IMAP (not Google and Microsoft) but I want to gather some data.

Log host and port on connection error

---

inbox/events/google.py
inbox/events/microsoft/graph_types.py
inbox/events/microsoft/parse.py
tests/events/microsoft/test_parse.py

Provides functions that convert Microsoft Graph Responses to sync-engine ORM objects.

Microsoft: parse_event, parse_calendar

---

inbox/events/abstract.py
inbox/events/google.py

This extract abstract events provider from GoogleEventsProvider. This will be later extended to implement MicrosofEventsProvider.

Microsoft: Extract AbstractEventsProvider

---

inbox/auth/utils.py
inbox/crispin.py
inbox/events/util.py
inbox/mailsync/backends/imap/generic.py
inbox/models/backends/generic.py
inbox/models/backends/imap.py
inbox/models/backends/oauth.py
inbox/models/event.py
inbox/models/message.py
inbox/models/secret.py
inbox/scheduling/event_queue.py
inbox/security/blobstorage.py
inbox/security/oracles.py
inbox/sendmail/base.py
inbox/sendmail/smtp/postel.py
inbox/sqlalchemy_ext/util.py
inbox/util/addr.py
inbox/util/blockstore.py
inbox/util/encoding.py
inbox/util/file.py
inbox/util/html.py
inbox/util/misc.py

I was originally planning on making that manually but I learnt by Googling that you can do it [automatically](https://github.com/ilevkivskyi/com2ann):
```sh
pipx install git+https://github.com/ilevkivskyi/com2ann.git 
com2ann inbox
```

Convert type comments to type annotations

---

inbox/auth/oauth.py

Just trying to get more clarity on what is happening in these cases.

Store original exception

---

inbox/events/abstract.py
inbox/events/microsoft/events_provider.py
inbox/events/microsoft/parse.py
inbox/mailsync/service.py
inbox/models/backends/oauth.py
inbox/models/backends/outlook.py
inbox/models/calendar.py
tests/events/microsoft/conftest.py
tests/events/microsoft/test_events_provider.py
tests/events/microsoft/test_graph_client.py
tests/events/microsoft/test_parse.py

This provides Minimum Viable Product™️ version of Microsoft Calendar Sync.
Currently supports:
* Singular events
* Recurring events (but without gaps and edits inside series yet)
Currently does not support:
* Webhook subscriptions (but it will resync every 5 minutes so changes eventually get there but just with a lot delay)
* Deletions
Tested this locally with CRM and things seem to be working just fine. More PRs to provide missing parts will follow.

Microsoft: Events provider MVP

---

inbox/events/microsoft/graph_client.py
tests/events/microsoft/test_graph_client.py

I noticed that Microsoft Graph API sporadically returns 503s and that subsequently it succeeds. I wired logic to retry 503s automatically every 5 seconds up to 10 times.

Microsoft: Automatically retry on 503

---

inbox/auth/oauth.py

Currently we just let the exception wind down the stack and we rely on the fact that sync-engine will eventually retry. This needlessly clutters the log and also makes a very loud Rollbar. Also does extra work and probably slows things a little down.
Those errors contain retry info you can use to sleep instead, and as sync-engine runs on gevent there's no problem with being polite to authalligator and respecting the retries.

Handle LOCK_ERROR and TRY_LATER

---

inbox/error_handling.py

This drops the logic we used to sample some noisy Rollbars.

Drop error sampling

---

requirements/test.txt

Needed for later versions of Python

Upgrade pytest deps

---

inbox/crispin.py

Resolves https://github.com/closeio/closeio/issues/31230

When raising GmailSettingsError store folder names

---

inbox/auth/oauth.py

For some accounts we get:
> Advanced Protection prevented your Google Account from signing in. This security feature stops most non-Google apps and services from accessing your data to keep your account protected.
I am not sure if this information is properly propogated to users. I need to know account_id at least to find out. It's common to attach account_id to logs in sync-engine.

Bind account_id to Google refresh token logic

---

docker-compose.yml

This updates the Redis version in docker-compose to 7.0.

Update Redis version in docker-compose

---

requirements/prod.txt

Contains:
* https://github.com/closeio/authalligator-client/pull/16
* https://github.com/closeio/authalligator-client/pull/15
No changes relevant to sync-engine here but we should keep this in sync.

Upgrade authalligator-client

---

inbox/api/kellogs.py
inbox/models/thread.py

After deploying https://github.com/closeio/sync-engine/pull/475 I realized there were more places I missed.

Don't break on missing categories #2

---

inbox/crispin.py

We have two accounts in production clusters that produce rather loud Rollbar. They are both hosted on a server called `SmarterMail` and it turns out that it does not implement IMAP according to the spec.
Here's a dump of an IMAP session with this server:
```
* OK IMAP4rev1 SmarterMail
01 CAPABILITY
* CAPABILITY IMAP4rev1 AUTH=CRAM-MD5 AUTH=NTLM AUTH=PLAIN SASL-IR UIDPLUS QUOTA MOVE XLIST CHILDREN ENABLE CONDSTORE
01 OK CAPABILITY completed
02 AUTHENTICATE PLAIN
+
[_REDACTED_]
02 OK PLAIN authentication successful
08 LIST "" *
* LIST (\HasChildren) "." INBOX
[_TRIMMED_ ...]
06 SELECT "INBOX"
* 36 EXISTS
* 0 RECENT
* OK [UNSEEN 2] Message 2 is first unseen
* OK [UIDVALIDITY 1] UIDs valid
* OK [UIDNEXT 37] Predicted next UID
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft \Recent)
* OK …
```

Add MODSEQ explicitely for SmarterMail

---

inbox/events/remote_sync.py

We had one of our sync-pods loop crashing this morning. After poking for a while at the logs I spotted that one of the greenlets is blocking a lot:
```
{
"frame":"  File \"/opt/app/inbox/sync/base_sync.py\", line 58, in _run\n    retry_with_logging(\n\t  File \"/opt/app/inbox/util/concurrency.py\", line 149, in retry_with_logging\n    return retry(\n\t  File \"/opt/app/inbox/util/concurrency.py\", line 71, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/opt/app/inbox/sync/base_sync.py\", line 78, in _run_impl\n    self.sync()\n\t  File \"/opt/app/inbox/events/remote_sync.py\", line 288, in sync\n    self._sync_data()\n\t  File \"/opt/app/inbox/events/remote_sync.py\", line 367, in _sync_data\n    _delete_calendar(db_session, calendar)\n\t  File …
```

Make sure we don't try to load all the calendar event objects into memory at once while deleting a calendar.

---

requirements/prod.txt

resolves https://github.com/closeio/sync-engine/security/dependabot/27
not sure why dependabot complains it can't find the dependency...

upgrade cryptography

---

inbox/events/google.py

Fixes [#410](https://github.com/closeio/closeio-nylas/issues/410)

Fix wrong assertion on exception handler

---

requirements/prod.txt

Jinja2 3.1.3

---

requirements/prod.txt

Pygments 2.17.2

---

.github/workflows/build-and-release.yaml

Fixes #
Summary:
Test Plan:
Reviewers:
Please add the reviewer as an assignee to this PR on the right

Remove python 3.7 from CI

---

tests/conftest.py

Cherry-picked from https://github.com/closeio/sync-engine/pull/655

Fix imports in conftest

---

inbox/contacts/processing.py
inbox/events/ical.py
inbox/mailsync/backends/imap/common.py
inbox/mailsync/backends/imap/generic.py
inbox/models/backends/imap.py
inbox/models/message.py
inbox/models/util.py
inbox/util/addr.py

This is a small cleanup that I wanted to do before extracting some of those methods out of the classes. I also added some types.

Clean up email parsing

---

bin/mysql-prompt.py

This exposes mysql client `--execute` and `--batch` options. `--execute` runs one off SQL commands on a single cluster without dropping to the interactive shell. This is especially useful when you need to connect to several clusters and do the same action on them. `--batch` makes sure that the output is in machine readable format, instead of the normal mysql tabular format.
Example:
```
docker-compose exec nylas_sync bin/mysql-prompt.py -e "SELECT VERSION(), NOW()"
+-----------+---------------------+
| VERSION() | NOW()               |
+-----------+---------------------+
| 8.0.29    | 2024-07-08 15:10:16 |
+-----------+---------------------+
```
Example with machine readable format, separate by tab
```
docker-compose exec nylas_sync bin/mysql-prompt.py -B -e "SELECT VERSION(), NOW()" …
```

Expose --execute and --batch

---

inbox/crispin.py
tests/imap/test_pooling.py

Sync-engine calls gevent.monkey.patch_all() before importing other modules.
`gevent.queue.Queue` APIs are a superset of stdlib `queue.Queue` APIs.
Sync-engine uses `items` convenience parameter of `gevent.queue.Queue` [initializer](https://github.com/gevent/gevent/blob/master/src/gevent/queue.py#L129) to prepulate queue elements. `queue.Queue` [initializer](https://github.com/python/cpython/blob/main/Lib/queue.py#L46) does not have this argument, but you can just put them right after initialization.
The tests rely on the fact that `gevent.queue.Queue` implements [iterator protocol](https://github.com/gevent/gevent/blob/a67891991c95b5ffca78dc1f1a11f956ec3963ca/src/gevent/queue.py#L408-L415) and stdlib does not, but you can just pop the elements to a list instead and check them.

Sync pods: Replace gevent.queue.Queue with queue.Queue

---

inbox/util/blockstore.py

There are no functional changes in this PR. The only reason I open this because I will need this structure to nicely write a recompression script.
This:
* Extracts `maybe_compress_raw_mime` from `save_raw_mime`.
* Extracts `maybe_decompress_raw_mime` from `get_raw_mime`.
* Adds an optional flag `overwrite=False` to `save_to_blockstore` and the functions it calls. This is because when recompressing I will need to overwrite the decompressed mime with the compressed one under the same SHA key.

Zstandard recompress preparatory refactor

---

bin/purge-transaction-log.py

This is another of our processes that can be trivially ported to threads. This PR is basically the same as [this PR](https://github.com/closeio/sync-engine/pull/895).
- Remove gevent monkey patching
- Use a threadpool instead of list of greenlets
- Don't use gevent APIs, only sleep here. joinall is not needed because the context manager waits for all the threads to end.

Drop gevent in purge transactions pod

---

inbox/mailsync/gc.py

As per your suggestion, it's definitely not worth breaking somebody's sync over this.

Handle ObjectDeleteError in DeleteHandler

---

inbox/api/ns_api.py
inbox/contacts/google.py
inbox/crispin.py
inbox/transactions/delta_sync.py
inbox/util/rdb.py

Some other miscellaneous places were gevent can be already removed.

Misc: Remove gevent

---

inbox/mailsync/backends/gmail.py
inbox/mailsync/backends/imap/generic.py

Most parts of the sync are stateful objects inheriting from greenlet base class. To remove gevent specific APIs and make the whole thing thread compatible it's easier to convert this to a subclass of greenlet as well. Threads support subclassing and have a `start()` method like greenlets. `kill()` method does not exist for threads but can be polyfilled later.

Sync: Extract ChangePoller

---

inbox/interruptible_threading.py

Still in the world of CFS throttling...
TLDR: When I ported from gevent to threading I implemented a "polyfill" for threads that implements the APIs very similar to greenlets (or at least the subset sync-engine uses). If you wanna read more on "interruptible threading" check out this [PR](https://github.com/closeio/sync-engine/pull/944). But if you don't feel like - there's gonna be a show & tell ;-)
Threads can not be killed or interrupted (in Python, can be generally in C with POSIX threads)  by another thread unless they cooperatively check from time to time if they are supposed to exit and then kindly exit.
Greenlets on the other hand can be interrupted e.g. by timeouts and can be also `kill()` ed. In gevent world every time you yield back to the loop (either by using gevent APIs or …

Use threading.Event() in "interruptible sleep"

---

requirements/requirements-prod.in
requirements/requirements-prod.txt

Addresses [CVE-2023-30861](https://nvd.nist.gov/vuln/detail/CVE-2023-30861)

Bump Flask

---

inbox/auth/utils.py

Small refactor for readability and (possibly) a marginal performance improvement. No changes in behavior.

Small improvement to auth functions
